ALTER TABLE "User"
ADD COLUMN "nudgeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastNudgeSentAt" TIMESTAMP(3),
ADD COLUMN "nudgingPaused" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "lastContactedAt" TIMESTAMP(3);
