
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const GreetingType = {
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON'
} as const

export type GreetingType = (typeof GreetingType)[keyof typeof GreetingType]


export const CatchupTier = {
  QUICK_FIX: 'QUICK_FIX',
  FULL_BACKLOG: 'FULL_BACKLOG',
  VIP_DEFENSE: 'VIP_DEFENSE'
} as const

export type CatchupTier = (typeof CatchupTier)[keyof typeof CatchupTier]


export const TimeframeType = {
  WEEKS: 'WEEKS',
  MONTHS: 'MONTHS'
} as const

export type TimeframeType = (typeof TimeframeType)[keyof typeof TimeframeType]


export const CatchupPaymentStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID'
} as const

export type CatchupPaymentStatus = (typeof CatchupPaymentStatus)[keyof typeof CatchupPaymentStatus]


export const TransactionStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]
