
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CatchupSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CatchupSession
 * 
 */
export type CatchupSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$CatchupSessionPayload>

export type AggregateCatchupSession = {
  _count: CatchupSessionCountAggregateOutputType | null
  _avg: CatchupSessionAvgAggregateOutputType | null
  _sum: CatchupSessionSumAggregateOutputType | null
  _min: CatchupSessionMinAggregateOutputType | null
  _max: CatchupSessionMaxAggregateOutputType | null
}

export type CatchupSessionAvgAggregateOutputType = {
  userId: number | null
  totalDuration: number | null
  currentBlock: number | null
}

export type CatchupSessionSumAggregateOutputType = {
  userId: number | null
  totalDuration: number | null
  currentBlock: number | null
}

export type CatchupSessionMinAggregateOutputType = {
  id: string | null
  userId: number | null
  tierSelected: $Enums.CatchupTier | null
  totalDuration: number | null
  currentBlock: number | null
  startDate: Date | null
  paymentStatus: $Enums.CatchupPaymentStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CatchupSessionMaxAggregateOutputType = {
  id: string | null
  userId: number | null
  tierSelected: $Enums.CatchupTier | null
  totalDuration: number | null
  currentBlock: number | null
  startDate: Date | null
  paymentStatus: $Enums.CatchupPaymentStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CatchupSessionCountAggregateOutputType = {
  id: number
  userId: number
  tierSelected: number
  totalDuration: number
  currentBlock: number
  startDate: number
  contextDump: number
  paymentStatus: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CatchupSessionAvgAggregateInputType = {
  userId?: true
  totalDuration?: true
  currentBlock?: true
}

export type CatchupSessionSumAggregateInputType = {
  userId?: true
  totalDuration?: true
  currentBlock?: true
}

export type CatchupSessionMinAggregateInputType = {
  id?: true
  userId?: true
  tierSelected?: true
  totalDuration?: true
  currentBlock?: true
  startDate?: true
  paymentStatus?: true
  createdAt?: true
  updatedAt?: true
}

export type CatchupSessionMaxAggregateInputType = {
  id?: true
  userId?: true
  tierSelected?: true
  totalDuration?: true
  currentBlock?: true
  startDate?: true
  paymentStatus?: true
  createdAt?: true
  updatedAt?: true
}

export type CatchupSessionCountAggregateInputType = {
  id?: true
  userId?: true
  tierSelected?: true
  totalDuration?: true
  currentBlock?: true
  startDate?: true
  contextDump?: true
  paymentStatus?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CatchupSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CatchupSession to aggregate.
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatchupSessions to fetch.
   */
  orderBy?: Prisma.CatchupSessionOrderByWithRelationInput | Prisma.CatchupSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CatchupSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatchupSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatchupSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CatchupSessions
  **/
  _count?: true | CatchupSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CatchupSessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CatchupSessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CatchupSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CatchupSessionMaxAggregateInputType
}

export type GetCatchupSessionAggregateType<T extends CatchupSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateCatchupSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCatchupSession[P]>
    : Prisma.GetScalarType<T[P], AggregateCatchupSession[P]>
}




export type CatchupSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CatchupSessionWhereInput
  orderBy?: Prisma.CatchupSessionOrderByWithAggregationInput | Prisma.CatchupSessionOrderByWithAggregationInput[]
  by: Prisma.CatchupSessionScalarFieldEnum[] | Prisma.CatchupSessionScalarFieldEnum
  having?: Prisma.CatchupSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CatchupSessionCountAggregateInputType | true
  _avg?: CatchupSessionAvgAggregateInputType
  _sum?: CatchupSessionSumAggregateInputType
  _min?: CatchupSessionMinAggregateInputType
  _max?: CatchupSessionMaxAggregateInputType
}

export type CatchupSessionGroupByOutputType = {
  id: string
  userId: number
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock: number
  startDate: Date
  contextDump: runtime.JsonValue | null
  paymentStatus: $Enums.CatchupPaymentStatus
  createdAt: Date
  updatedAt: Date
  _count: CatchupSessionCountAggregateOutputType | null
  _avg: CatchupSessionAvgAggregateOutputType | null
  _sum: CatchupSessionSumAggregateOutputType | null
  _min: CatchupSessionMinAggregateOutputType | null
  _max: CatchupSessionMaxAggregateOutputType | null
}

export type GetCatchupSessionGroupByPayload<T extends CatchupSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CatchupSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CatchupSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CatchupSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CatchupSessionGroupByOutputType[P]>
      }
    >
  >



export type CatchupSessionWhereInput = {
  AND?: Prisma.CatchupSessionWhereInput | Prisma.CatchupSessionWhereInput[]
  OR?: Prisma.CatchupSessionWhereInput[]
  NOT?: Prisma.CatchupSessionWhereInput | Prisma.CatchupSessionWhereInput[]
  id?: Prisma.StringFilter<"CatchupSession"> | string
  userId?: Prisma.IntFilter<"CatchupSession"> | number
  tierSelected?: Prisma.EnumCatchupTierFilter<"CatchupSession"> | $Enums.CatchupTier
  totalDuration?: Prisma.IntFilter<"CatchupSession"> | number
  currentBlock?: Prisma.IntFilter<"CatchupSession"> | number
  startDate?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  contextDump?: Prisma.JsonNullableFilter<"CatchupSession">
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFilter<"CatchupSession"> | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CatchupSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tierSelected?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  contextDump?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type CatchupSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CatchupSessionWhereInput | Prisma.CatchupSessionWhereInput[]
  OR?: Prisma.CatchupSessionWhereInput[]
  NOT?: Prisma.CatchupSessionWhereInput | Prisma.CatchupSessionWhereInput[]
  userId?: Prisma.IntFilter<"CatchupSession"> | number
  tierSelected?: Prisma.EnumCatchupTierFilter<"CatchupSession"> | $Enums.CatchupTier
  totalDuration?: Prisma.IntFilter<"CatchupSession"> | number
  currentBlock?: Prisma.IntFilter<"CatchupSession"> | number
  startDate?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  contextDump?: Prisma.JsonNullableFilter<"CatchupSession">
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFilter<"CatchupSession"> | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type CatchupSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tierSelected?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  contextDump?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CatchupSessionCountOrderByAggregateInput
  _avg?: Prisma.CatchupSessionAvgOrderByAggregateInput
  _max?: Prisma.CatchupSessionMaxOrderByAggregateInput
  _min?: Prisma.CatchupSessionMinOrderByAggregateInput
  _sum?: Prisma.CatchupSessionSumOrderByAggregateInput
}

export type CatchupSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.CatchupSessionScalarWhereWithAggregatesInput | Prisma.CatchupSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.CatchupSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CatchupSessionScalarWhereWithAggregatesInput | Prisma.CatchupSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CatchupSession"> | string
  userId?: Prisma.IntWithAggregatesFilter<"CatchupSession"> | number
  tierSelected?: Prisma.EnumCatchupTierWithAggregatesFilter<"CatchupSession"> | $Enums.CatchupTier
  totalDuration?: Prisma.IntWithAggregatesFilter<"CatchupSession"> | number
  currentBlock?: Prisma.IntWithAggregatesFilter<"CatchupSession"> | number
  startDate?: Prisma.DateTimeWithAggregatesFilter<"CatchupSession"> | Date | string
  contextDump?: Prisma.JsonNullableWithAggregatesFilter<"CatchupSession">
  paymentStatus?: Prisma.EnumCatchupPaymentStatusWithAggregatesFilter<"CatchupSession"> | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CatchupSession"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CatchupSession"> | Date | string
}

export type CatchupSessionCreateInput = {
  id?: string
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCatchupSessionsInput
}

export type CatchupSessionUncheckedCreateInput = {
  id?: string
  userId: number
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatchupSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCatchupSessionsNestedInput
}

export type CatchupSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatchupSessionCreateManyInput = {
  id?: string
  userId: number
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatchupSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatchupSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatchupSessionListRelationFilter = {
  every?: Prisma.CatchupSessionWhereInput
  some?: Prisma.CatchupSessionWhereInput
  none?: Prisma.CatchupSessionWhereInput
}

export type CatchupSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CatchupSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tierSelected?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  contextDump?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatchupSessionAvgOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
}

export type CatchupSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tierSelected?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatchupSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tierSelected?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatchupSessionSumOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  totalDuration?: Prisma.SortOrder
  currentBlock?: Prisma.SortOrder
}

export type CatchupSessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput> | Prisma.CatchupSessionCreateWithoutUserInput[] | Prisma.CatchupSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CatchupSessionCreateOrConnectWithoutUserInput | Prisma.CatchupSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CatchupSessionCreateManyUserInputEnvelope
  connect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
}

export type CatchupSessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput> | Prisma.CatchupSessionCreateWithoutUserInput[] | Prisma.CatchupSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CatchupSessionCreateOrConnectWithoutUserInput | Prisma.CatchupSessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CatchupSessionCreateManyUserInputEnvelope
  connect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
}

export type CatchupSessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput> | Prisma.CatchupSessionCreateWithoutUserInput[] | Prisma.CatchupSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CatchupSessionCreateOrConnectWithoutUserInput | Prisma.CatchupSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CatchupSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.CatchupSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CatchupSessionCreateManyUserInputEnvelope
  set?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  disconnect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  delete?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  connect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  update?: Prisma.CatchupSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.CatchupSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CatchupSessionUpdateManyWithWhereWithoutUserInput | Prisma.CatchupSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CatchupSessionScalarWhereInput | Prisma.CatchupSessionScalarWhereInput[]
}

export type CatchupSessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput> | Prisma.CatchupSessionCreateWithoutUserInput[] | Prisma.CatchupSessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CatchupSessionCreateOrConnectWithoutUserInput | Prisma.CatchupSessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CatchupSessionUpsertWithWhereUniqueWithoutUserInput | Prisma.CatchupSessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CatchupSessionCreateManyUserInputEnvelope
  set?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  disconnect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  delete?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  connect?: Prisma.CatchupSessionWhereUniqueInput | Prisma.CatchupSessionWhereUniqueInput[]
  update?: Prisma.CatchupSessionUpdateWithWhereUniqueWithoutUserInput | Prisma.CatchupSessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CatchupSessionUpdateManyWithWhereWithoutUserInput | Prisma.CatchupSessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CatchupSessionScalarWhereInput | Prisma.CatchupSessionScalarWhereInput[]
}

export type EnumCatchupTierFieldUpdateOperationsInput = {
  set?: $Enums.CatchupTier
}

export type EnumCatchupPaymentStatusFieldUpdateOperationsInput = {
  set?: $Enums.CatchupPaymentStatus
}

export type CatchupSessionCreateWithoutUserInput = {
  id?: string
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatchupSessionUncheckedCreateWithoutUserInput = {
  id?: string
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatchupSessionCreateOrConnectWithoutUserInput = {
  where: Prisma.CatchupSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput>
}

export type CatchupSessionCreateManyUserInputEnvelope = {
  data: Prisma.CatchupSessionCreateManyUserInput | Prisma.CatchupSessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CatchupSessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CatchupSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.CatchupSessionUpdateWithoutUserInput, Prisma.CatchupSessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CatchupSessionCreateWithoutUserInput, Prisma.CatchupSessionUncheckedCreateWithoutUserInput>
}

export type CatchupSessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CatchupSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.CatchupSessionUpdateWithoutUserInput, Prisma.CatchupSessionUncheckedUpdateWithoutUserInput>
}

export type CatchupSessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CatchupSessionScalarWhereInput
  data: Prisma.XOR<Prisma.CatchupSessionUpdateManyMutationInput, Prisma.CatchupSessionUncheckedUpdateManyWithoutUserInput>
}

export type CatchupSessionScalarWhereInput = {
  AND?: Prisma.CatchupSessionScalarWhereInput | Prisma.CatchupSessionScalarWhereInput[]
  OR?: Prisma.CatchupSessionScalarWhereInput[]
  NOT?: Prisma.CatchupSessionScalarWhereInput | Prisma.CatchupSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"CatchupSession"> | string
  userId?: Prisma.IntFilter<"CatchupSession"> | number
  tierSelected?: Prisma.EnumCatchupTierFilter<"CatchupSession"> | $Enums.CatchupTier
  totalDuration?: Prisma.IntFilter<"CatchupSession"> | number
  currentBlock?: Prisma.IntFilter<"CatchupSession"> | number
  startDate?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  contextDump?: Prisma.JsonNullableFilter<"CatchupSession">
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFilter<"CatchupSession"> | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CatchupSession"> | Date | string
}

export type CatchupSessionCreateManyUserInput = {
  id?: string
  tierSelected: $Enums.CatchupTier
  totalDuration: number
  currentBlock?: number
  startDate: Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: $Enums.CatchupPaymentStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatchupSessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatchupSessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatchupSessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tierSelected?: Prisma.EnumCatchupTierFieldUpdateOperationsInput | $Enums.CatchupTier
  totalDuration?: Prisma.IntFieldUpdateOperationsInput | number
  currentBlock?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contextDump?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  paymentStatus?: Prisma.EnumCatchupPaymentStatusFieldUpdateOperationsInput | $Enums.CatchupPaymentStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CatchupSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tierSelected?: boolean
  totalDuration?: boolean
  currentBlock?: boolean
  startDate?: boolean
  contextDump?: boolean
  paymentStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["catchupSession"]>

export type CatchupSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tierSelected?: boolean
  totalDuration?: boolean
  currentBlock?: boolean
  startDate?: boolean
  contextDump?: boolean
  paymentStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["catchupSession"]>

export type CatchupSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tierSelected?: boolean
  totalDuration?: boolean
  currentBlock?: boolean
  startDate?: boolean
  contextDump?: boolean
  paymentStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["catchupSession"]>

export type CatchupSessionSelectScalar = {
  id?: boolean
  userId?: boolean
  tierSelected?: boolean
  totalDuration?: boolean
  currentBlock?: boolean
  startDate?: boolean
  contextDump?: boolean
  paymentStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CatchupSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "tierSelected" | "totalDuration" | "currentBlock" | "startDate" | "contextDump" | "paymentStatus" | "createdAt" | "updatedAt", ExtArgs["result"]["catchupSession"]>
export type CatchupSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CatchupSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CatchupSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CatchupSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CatchupSession"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: number
    tierSelected: $Enums.CatchupTier
    totalDuration: number
    currentBlock: number
    startDate: Date
    contextDump: runtime.JsonValue | null
    paymentStatus: $Enums.CatchupPaymentStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["catchupSession"]>
  composites: {}
}

export type CatchupSessionGetPayload<S extends boolean | null | undefined | CatchupSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload, S>

export type CatchupSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CatchupSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CatchupSessionCountAggregateInputType | true
  }

export interface CatchupSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CatchupSession'], meta: { name: 'CatchupSession' } }
  /**
   * Find zero or one CatchupSession that matches the filter.
   * @param {CatchupSessionFindUniqueArgs} args - Arguments to find a CatchupSession
   * @example
   * // Get one CatchupSession
   * const catchupSession = await prisma.catchupSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CatchupSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, CatchupSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CatchupSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CatchupSessionFindUniqueOrThrowArgs} args - Arguments to find a CatchupSession
   * @example
   * // Get one CatchupSession
   * const catchupSession = await prisma.catchupSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CatchupSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CatchupSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CatchupSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionFindFirstArgs} args - Arguments to find a CatchupSession
   * @example
   * // Get one CatchupSession
   * const catchupSession = await prisma.catchupSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CatchupSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, CatchupSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CatchupSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionFindFirstOrThrowArgs} args - Arguments to find a CatchupSession
   * @example
   * // Get one CatchupSession
   * const catchupSession = await prisma.catchupSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CatchupSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CatchupSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CatchupSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CatchupSessions
   * const catchupSessions = await prisma.catchupSession.findMany()
   * 
   * // Get first 10 CatchupSessions
   * const catchupSessions = await prisma.catchupSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const catchupSessionWithIdOnly = await prisma.catchupSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CatchupSessionFindManyArgs>(args?: Prisma.SelectSubset<T, CatchupSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CatchupSession.
   * @param {CatchupSessionCreateArgs} args - Arguments to create a CatchupSession.
   * @example
   * // Create one CatchupSession
   * const CatchupSession = await prisma.catchupSession.create({
   *   data: {
   *     // ... data to create a CatchupSession
   *   }
   * })
   * 
   */
  create<T extends CatchupSessionCreateArgs>(args: Prisma.SelectSubset<T, CatchupSessionCreateArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CatchupSessions.
   * @param {CatchupSessionCreateManyArgs} args - Arguments to create many CatchupSessions.
   * @example
   * // Create many CatchupSessions
   * const catchupSession = await prisma.catchupSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CatchupSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, CatchupSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CatchupSessions and returns the data saved in the database.
   * @param {CatchupSessionCreateManyAndReturnArgs} args - Arguments to create many CatchupSessions.
   * @example
   * // Create many CatchupSessions
   * const catchupSession = await prisma.catchupSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CatchupSessions and only return the `id`
   * const catchupSessionWithIdOnly = await prisma.catchupSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CatchupSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CatchupSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CatchupSession.
   * @param {CatchupSessionDeleteArgs} args - Arguments to delete one CatchupSession.
   * @example
   * // Delete one CatchupSession
   * const CatchupSession = await prisma.catchupSession.delete({
   *   where: {
   *     // ... filter to delete one CatchupSession
   *   }
   * })
   * 
   */
  delete<T extends CatchupSessionDeleteArgs>(args: Prisma.SelectSubset<T, CatchupSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CatchupSession.
   * @param {CatchupSessionUpdateArgs} args - Arguments to update one CatchupSession.
   * @example
   * // Update one CatchupSession
   * const catchupSession = await prisma.catchupSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CatchupSessionUpdateArgs>(args: Prisma.SelectSubset<T, CatchupSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CatchupSessions.
   * @param {CatchupSessionDeleteManyArgs} args - Arguments to filter CatchupSessions to delete.
   * @example
   * // Delete a few CatchupSessions
   * const { count } = await prisma.catchupSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CatchupSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, CatchupSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CatchupSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CatchupSessions
   * const catchupSession = await prisma.catchupSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CatchupSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, CatchupSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CatchupSessions and returns the data updated in the database.
   * @param {CatchupSessionUpdateManyAndReturnArgs} args - Arguments to update many CatchupSessions.
   * @example
   * // Update many CatchupSessions
   * const catchupSession = await prisma.catchupSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CatchupSessions and only return the `id`
   * const catchupSessionWithIdOnly = await prisma.catchupSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CatchupSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CatchupSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CatchupSession.
   * @param {CatchupSessionUpsertArgs} args - Arguments to update or create a CatchupSession.
   * @example
   * // Update or create a CatchupSession
   * const catchupSession = await prisma.catchupSession.upsert({
   *   create: {
   *     // ... data to create a CatchupSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CatchupSession we want to update
   *   }
   * })
   */
  upsert<T extends CatchupSessionUpsertArgs>(args: Prisma.SelectSubset<T, CatchupSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__CatchupSessionClient<runtime.Types.Result.GetResult<Prisma.$CatchupSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CatchupSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionCountArgs} args - Arguments to filter CatchupSessions to count.
   * @example
   * // Count the number of CatchupSessions
   * const count = await prisma.catchupSession.count({
   *   where: {
   *     // ... the filter for the CatchupSessions we want to count
   *   }
   * })
  **/
  count<T extends CatchupSessionCountArgs>(
    args?: Prisma.Subset<T, CatchupSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CatchupSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CatchupSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CatchupSessionAggregateArgs>(args: Prisma.Subset<T, CatchupSessionAggregateArgs>): Prisma.PrismaPromise<GetCatchupSessionAggregateType<T>>

  /**
   * Group by CatchupSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatchupSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CatchupSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CatchupSessionGroupByArgs['orderBy'] }
      : { orderBy?: CatchupSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CatchupSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCatchupSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CatchupSession model
 */
readonly fields: CatchupSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CatchupSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CatchupSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CatchupSession model
 */
export interface CatchupSessionFieldRefs {
  readonly id: Prisma.FieldRef<"CatchupSession", 'String'>
  readonly userId: Prisma.FieldRef<"CatchupSession", 'Int'>
  readonly tierSelected: Prisma.FieldRef<"CatchupSession", 'CatchupTier'>
  readonly totalDuration: Prisma.FieldRef<"CatchupSession", 'Int'>
  readonly currentBlock: Prisma.FieldRef<"CatchupSession", 'Int'>
  readonly startDate: Prisma.FieldRef<"CatchupSession", 'DateTime'>
  readonly contextDump: Prisma.FieldRef<"CatchupSession", 'Json'>
  readonly paymentStatus: Prisma.FieldRef<"CatchupSession", 'CatchupPaymentStatus'>
  readonly createdAt: Prisma.FieldRef<"CatchupSession", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CatchupSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CatchupSession findUnique
 */
export type CatchupSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter, which CatchupSession to fetch.
   */
  where: Prisma.CatchupSessionWhereUniqueInput
}

/**
 * CatchupSession findUniqueOrThrow
 */
export type CatchupSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter, which CatchupSession to fetch.
   */
  where: Prisma.CatchupSessionWhereUniqueInput
}

/**
 * CatchupSession findFirst
 */
export type CatchupSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter, which CatchupSession to fetch.
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatchupSessions to fetch.
   */
  orderBy?: Prisma.CatchupSessionOrderByWithRelationInput | Prisma.CatchupSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CatchupSessions.
   */
  cursor?: Prisma.CatchupSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatchupSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatchupSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CatchupSessions.
   */
  distinct?: Prisma.CatchupSessionScalarFieldEnum | Prisma.CatchupSessionScalarFieldEnum[]
}

/**
 * CatchupSession findFirstOrThrow
 */
export type CatchupSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter, which CatchupSession to fetch.
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatchupSessions to fetch.
   */
  orderBy?: Prisma.CatchupSessionOrderByWithRelationInput | Prisma.CatchupSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CatchupSessions.
   */
  cursor?: Prisma.CatchupSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatchupSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatchupSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CatchupSessions.
   */
  distinct?: Prisma.CatchupSessionScalarFieldEnum | Prisma.CatchupSessionScalarFieldEnum[]
}

/**
 * CatchupSession findMany
 */
export type CatchupSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter, which CatchupSessions to fetch.
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatchupSessions to fetch.
   */
  orderBy?: Prisma.CatchupSessionOrderByWithRelationInput | Prisma.CatchupSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CatchupSessions.
   */
  cursor?: Prisma.CatchupSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatchupSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatchupSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CatchupSessions.
   */
  distinct?: Prisma.CatchupSessionScalarFieldEnum | Prisma.CatchupSessionScalarFieldEnum[]
}

/**
 * CatchupSession create
 */
export type CatchupSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a CatchupSession.
   */
  data: Prisma.XOR<Prisma.CatchupSessionCreateInput, Prisma.CatchupSessionUncheckedCreateInput>
}

/**
 * CatchupSession createMany
 */
export type CatchupSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CatchupSessions.
   */
  data: Prisma.CatchupSessionCreateManyInput | Prisma.CatchupSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CatchupSession createManyAndReturn
 */
export type CatchupSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * The data used to create many CatchupSessions.
   */
  data: Prisma.CatchupSessionCreateManyInput | Prisma.CatchupSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CatchupSession update
 */
export type CatchupSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a CatchupSession.
   */
  data: Prisma.XOR<Prisma.CatchupSessionUpdateInput, Prisma.CatchupSessionUncheckedUpdateInput>
  /**
   * Choose, which CatchupSession to update.
   */
  where: Prisma.CatchupSessionWhereUniqueInput
}

/**
 * CatchupSession updateMany
 */
export type CatchupSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CatchupSessions.
   */
  data: Prisma.XOR<Prisma.CatchupSessionUpdateManyMutationInput, Prisma.CatchupSessionUncheckedUpdateManyInput>
  /**
   * Filter which CatchupSessions to update
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * Limit how many CatchupSessions to update.
   */
  limit?: number
}

/**
 * CatchupSession updateManyAndReturn
 */
export type CatchupSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * The data used to update CatchupSessions.
   */
  data: Prisma.XOR<Prisma.CatchupSessionUpdateManyMutationInput, Prisma.CatchupSessionUncheckedUpdateManyInput>
  /**
   * Filter which CatchupSessions to update
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * Limit how many CatchupSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CatchupSession upsert
 */
export type CatchupSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the CatchupSession to update in case it exists.
   */
  where: Prisma.CatchupSessionWhereUniqueInput
  /**
   * In case the CatchupSession found by the `where` argument doesn't exist, create a new CatchupSession with this data.
   */
  create: Prisma.XOR<Prisma.CatchupSessionCreateInput, Prisma.CatchupSessionUncheckedCreateInput>
  /**
   * In case the CatchupSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CatchupSessionUpdateInput, Prisma.CatchupSessionUncheckedUpdateInput>
}

/**
 * CatchupSession delete
 */
export type CatchupSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
  /**
   * Filter which CatchupSession to delete.
   */
  where: Prisma.CatchupSessionWhereUniqueInput
}

/**
 * CatchupSession deleteMany
 */
export type CatchupSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CatchupSessions to delete
   */
  where?: Prisma.CatchupSessionWhereInput
  /**
   * Limit how many CatchupSessions to delete.
   */
  limit?: number
}

/**
 * CatchupSession without action
 */
export type CatchupSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatchupSession
   */
  select?: Prisma.CatchupSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatchupSession
   */
  omit?: Prisma.CatchupSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatchupSessionInclude<ExtArgs> | null
}
