
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ManualPayment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ManualPayment
 * 
 */
export type ManualPaymentModel = runtime.Types.Result.DefaultSelection<Prisma.$ManualPaymentPayload>

export type AggregateManualPayment = {
  _count: ManualPaymentCountAggregateOutputType | null
  _avg: ManualPaymentAvgAggregateOutputType | null
  _sum: ManualPaymentSumAggregateOutputType | null
  _min: ManualPaymentMinAggregateOutputType | null
  _max: ManualPaymentMaxAggregateOutputType | null
}

export type ManualPaymentAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type ManualPaymentSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type ManualPaymentMinAggregateOutputType = {
  id: number | null
  userId: number | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManualPaymentMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ManualPaymentCountAggregateOutputType = {
  id: number
  userId: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ManualPaymentAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type ManualPaymentSumAggregateInputType = {
  id?: true
  userId?: true
}

export type ManualPaymentMinAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ManualPaymentMaxAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ManualPaymentCountAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ManualPaymentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManualPayment to aggregate.
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualPayments to fetch.
   */
  orderBy?: Prisma.ManualPaymentOrderByWithRelationInput | Prisma.ManualPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManualPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ManualPayments
  **/
  _count?: true | ManualPaymentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ManualPaymentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ManualPaymentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManualPaymentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManualPaymentMaxAggregateInputType
}

export type GetManualPaymentAggregateType<T extends ManualPaymentAggregateArgs> = {
      [P in keyof T & keyof AggregateManualPayment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManualPayment[P]>
    : Prisma.GetScalarType<T[P], AggregateManualPayment[P]>
}




export type ManualPaymentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManualPaymentWhereInput
  orderBy?: Prisma.ManualPaymentOrderByWithAggregationInput | Prisma.ManualPaymentOrderByWithAggregationInput[]
  by: Prisma.ManualPaymentScalarFieldEnum[] | Prisma.ManualPaymentScalarFieldEnum
  having?: Prisma.ManualPaymentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManualPaymentCountAggregateInputType | true
  _avg?: ManualPaymentAvgAggregateInputType
  _sum?: ManualPaymentSumAggregateInputType
  _min?: ManualPaymentMinAggregateInputType
  _max?: ManualPaymentMaxAggregateInputType
}

export type ManualPaymentGroupByOutputType = {
  id: number
  userId: number
  status: string
  createdAt: Date
  updatedAt: Date
  _count: ManualPaymentCountAggregateOutputType | null
  _avg: ManualPaymentAvgAggregateOutputType | null
  _sum: ManualPaymentSumAggregateOutputType | null
  _min: ManualPaymentMinAggregateOutputType | null
  _max: ManualPaymentMaxAggregateOutputType | null
}

type GetManualPaymentGroupByPayload<T extends ManualPaymentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManualPaymentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManualPaymentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManualPaymentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManualPaymentGroupByOutputType[P]>
      }
    >
  >



export type ManualPaymentWhereInput = {
  AND?: Prisma.ManualPaymentWhereInput | Prisma.ManualPaymentWhereInput[]
  OR?: Prisma.ManualPaymentWhereInput[]
  NOT?: Prisma.ManualPaymentWhereInput | Prisma.ManualPaymentWhereInput[]
  id?: Prisma.IntFilter<"ManualPayment"> | number
  userId?: Prisma.IntFilter<"ManualPayment"> | number
  status?: Prisma.StringFilter<"ManualPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ManualPaymentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type ManualPaymentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ManualPaymentWhereInput | Prisma.ManualPaymentWhereInput[]
  OR?: Prisma.ManualPaymentWhereInput[]
  NOT?: Prisma.ManualPaymentWhereInput | Prisma.ManualPaymentWhereInput[]
  userId?: Prisma.IntFilter<"ManualPayment"> | number
  status?: Prisma.StringFilter<"ManualPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ManualPaymentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ManualPaymentCountOrderByAggregateInput
  _avg?: Prisma.ManualPaymentAvgOrderByAggregateInput
  _max?: Prisma.ManualPaymentMaxOrderByAggregateInput
  _min?: Prisma.ManualPaymentMinOrderByAggregateInput
  _sum?: Prisma.ManualPaymentSumOrderByAggregateInput
}

export type ManualPaymentScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManualPaymentScalarWhereWithAggregatesInput | Prisma.ManualPaymentScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManualPaymentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManualPaymentScalarWhereWithAggregatesInput | Prisma.ManualPaymentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ManualPayment"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ManualPayment"> | number
  status?: Prisma.StringWithAggregatesFilter<"ManualPayment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ManualPayment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ManualPayment"> | Date | string
}

export type ManualPaymentCreateInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutManualPaymentsInput
}

export type ManualPaymentUncheckedCreateInput = {
  id?: number
  userId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManualPaymentUpdateInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutManualPaymentsNestedInput
}

export type ManualPaymentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManualPaymentCreateManyInput = {
  id?: number
  userId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManualPaymentUpdateManyMutationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManualPaymentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManualPaymentListRelationFilter = {
  every?: Prisma.ManualPaymentWhereInput
  some?: Prisma.ManualPaymentWhereInput
  none?: Prisma.ManualPaymentWhereInput
}

export type ManualPaymentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ManualPaymentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManualPaymentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ManualPaymentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManualPaymentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ManualPaymentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ManualPaymentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput> | Prisma.ManualPaymentCreateWithoutUserInput[] | Prisma.ManualPaymentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ManualPaymentCreateOrConnectWithoutUserInput | Prisma.ManualPaymentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ManualPaymentCreateManyUserInputEnvelope
  connect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
}

export type ManualPaymentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput> | Prisma.ManualPaymentCreateWithoutUserInput[] | Prisma.ManualPaymentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ManualPaymentCreateOrConnectWithoutUserInput | Prisma.ManualPaymentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ManualPaymentCreateManyUserInputEnvelope
  connect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
}

export type ManualPaymentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput> | Prisma.ManualPaymentCreateWithoutUserInput[] | Prisma.ManualPaymentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ManualPaymentCreateOrConnectWithoutUserInput | Prisma.ManualPaymentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ManualPaymentUpsertWithWhereUniqueWithoutUserInput | Prisma.ManualPaymentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ManualPaymentCreateManyUserInputEnvelope
  set?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  disconnect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  delete?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  connect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  update?: Prisma.ManualPaymentUpdateWithWhereUniqueWithoutUserInput | Prisma.ManualPaymentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ManualPaymentUpdateManyWithWhereWithoutUserInput | Prisma.ManualPaymentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ManualPaymentScalarWhereInput | Prisma.ManualPaymentScalarWhereInput[]
}

export type ManualPaymentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput> | Prisma.ManualPaymentCreateWithoutUserInput[] | Prisma.ManualPaymentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ManualPaymentCreateOrConnectWithoutUserInput | Prisma.ManualPaymentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ManualPaymentUpsertWithWhereUniqueWithoutUserInput | Prisma.ManualPaymentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ManualPaymentCreateManyUserInputEnvelope
  set?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  disconnect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  delete?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  connect?: Prisma.ManualPaymentWhereUniqueInput | Prisma.ManualPaymentWhereUniqueInput[]
  update?: Prisma.ManualPaymentUpdateWithWhereUniqueWithoutUserInput | Prisma.ManualPaymentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ManualPaymentUpdateManyWithWhereWithoutUserInput | Prisma.ManualPaymentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ManualPaymentScalarWhereInput | Prisma.ManualPaymentScalarWhereInput[]
}

export type ManualPaymentCreateWithoutUserInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManualPaymentUncheckedCreateWithoutUserInput = {
  id?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManualPaymentCreateOrConnectWithoutUserInput = {
  where: Prisma.ManualPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput>
}

export type ManualPaymentCreateManyUserInputEnvelope = {
  data: Prisma.ManualPaymentCreateManyUserInput | Prisma.ManualPaymentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ManualPaymentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ManualPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.ManualPaymentUpdateWithoutUserInput, Prisma.ManualPaymentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ManualPaymentCreateWithoutUserInput, Prisma.ManualPaymentUncheckedCreateWithoutUserInput>
}

export type ManualPaymentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ManualPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.ManualPaymentUpdateWithoutUserInput, Prisma.ManualPaymentUncheckedUpdateWithoutUserInput>
}

export type ManualPaymentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ManualPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.ManualPaymentUpdateManyMutationInput, Prisma.ManualPaymentUncheckedUpdateManyWithoutUserInput>
}

export type ManualPaymentScalarWhereInput = {
  AND?: Prisma.ManualPaymentScalarWhereInput | Prisma.ManualPaymentScalarWhereInput[]
  OR?: Prisma.ManualPaymentScalarWhereInput[]
  NOT?: Prisma.ManualPaymentScalarWhereInput | Prisma.ManualPaymentScalarWhereInput[]
  id?: Prisma.IntFilter<"ManualPayment"> | number
  userId?: Prisma.IntFilter<"ManualPayment"> | number
  status?: Prisma.StringFilter<"ManualPayment"> | string
  createdAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ManualPayment"> | Date | string
}

export type ManualPaymentCreateManyUserInput = {
  id?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ManualPaymentUpdateWithoutUserInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManualPaymentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ManualPaymentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ManualPaymentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manualPayment"]>

export type ManualPaymentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manualPayment"]>

export type ManualPaymentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manualPayment"]>

export type ManualPaymentSelectScalar = {
  id?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ManualPaymentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["manualPayment"]>
export type ManualPaymentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ManualPaymentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ManualPaymentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ManualPaymentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ManualPayment"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["manualPayment"]>
  composites: {}
}

export type ManualPaymentGetPayload<S extends boolean | null | undefined | ManualPaymentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload, S>

export type ManualPaymentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManualPaymentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManualPaymentCountAggregateInputType | true
  }

export interface ManualPaymentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ManualPayment'], meta: { name: 'ManualPayment' } }
  /**
   * Find zero or one ManualPayment that matches the filter.
   * @param {ManualPaymentFindUniqueArgs} args - Arguments to find a ManualPayment
   * @example
   * // Get one ManualPayment
   * const manualPayment = await prisma.manualPayment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManualPaymentFindUniqueArgs>(args: Prisma.SelectSubset<T, ManualPaymentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ManualPayment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManualPaymentFindUniqueOrThrowArgs} args - Arguments to find a ManualPayment
   * @example
   * // Get one ManualPayment
   * const manualPayment = await prisma.manualPayment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManualPaymentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManualPaymentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManualPayment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentFindFirstArgs} args - Arguments to find a ManualPayment
   * @example
   * // Get one ManualPayment
   * const manualPayment = await prisma.manualPayment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManualPaymentFindFirstArgs>(args?: Prisma.SelectSubset<T, ManualPaymentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManualPayment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentFindFirstOrThrowArgs} args - Arguments to find a ManualPayment
   * @example
   * // Get one ManualPayment
   * const manualPayment = await prisma.manualPayment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManualPaymentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManualPaymentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ManualPayments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ManualPayments
   * const manualPayments = await prisma.manualPayment.findMany()
   * 
   * // Get first 10 ManualPayments
   * const manualPayments = await prisma.manualPayment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const manualPaymentWithIdOnly = await prisma.manualPayment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManualPaymentFindManyArgs>(args?: Prisma.SelectSubset<T, ManualPaymentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ManualPayment.
   * @param {ManualPaymentCreateArgs} args - Arguments to create a ManualPayment.
   * @example
   * // Create one ManualPayment
   * const ManualPayment = await prisma.manualPayment.create({
   *   data: {
   *     // ... data to create a ManualPayment
   *   }
   * })
   * 
   */
  create<T extends ManualPaymentCreateArgs>(args: Prisma.SelectSubset<T, ManualPaymentCreateArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ManualPayments.
   * @param {ManualPaymentCreateManyArgs} args - Arguments to create many ManualPayments.
   * @example
   * // Create many ManualPayments
   * const manualPayment = await prisma.manualPayment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManualPaymentCreateManyArgs>(args?: Prisma.SelectSubset<T, ManualPaymentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ManualPayments and returns the data saved in the database.
   * @param {ManualPaymentCreateManyAndReturnArgs} args - Arguments to create many ManualPayments.
   * @example
   * // Create many ManualPayments
   * const manualPayment = await prisma.manualPayment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ManualPayments and only return the `id`
   * const manualPaymentWithIdOnly = await prisma.manualPayment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManualPaymentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManualPaymentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ManualPayment.
   * @param {ManualPaymentDeleteArgs} args - Arguments to delete one ManualPayment.
   * @example
   * // Delete one ManualPayment
   * const ManualPayment = await prisma.manualPayment.delete({
   *   where: {
   *     // ... filter to delete one ManualPayment
   *   }
   * })
   * 
   */
  delete<T extends ManualPaymentDeleteArgs>(args: Prisma.SelectSubset<T, ManualPaymentDeleteArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ManualPayment.
   * @param {ManualPaymentUpdateArgs} args - Arguments to update one ManualPayment.
   * @example
   * // Update one ManualPayment
   * const manualPayment = await prisma.manualPayment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManualPaymentUpdateArgs>(args: Prisma.SelectSubset<T, ManualPaymentUpdateArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ManualPayments.
   * @param {ManualPaymentDeleteManyArgs} args - Arguments to filter ManualPayments to delete.
   * @example
   * // Delete a few ManualPayments
   * const { count } = await prisma.manualPayment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManualPaymentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManualPaymentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManualPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ManualPayments
   * const manualPayment = await prisma.manualPayment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManualPaymentUpdateManyArgs>(args: Prisma.SelectSubset<T, ManualPaymentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManualPayments and returns the data updated in the database.
   * @param {ManualPaymentUpdateManyAndReturnArgs} args - Arguments to update many ManualPayments.
   * @example
   * // Update many ManualPayments
   * const manualPayment = await prisma.manualPayment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ManualPayments and only return the `id`
   * const manualPaymentWithIdOnly = await prisma.manualPayment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManualPaymentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManualPaymentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ManualPayment.
   * @param {ManualPaymentUpsertArgs} args - Arguments to update or create a ManualPayment.
   * @example
   * // Update or create a ManualPayment
   * const manualPayment = await prisma.manualPayment.upsert({
   *   create: {
   *     // ... data to create a ManualPayment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ManualPayment we want to update
   *   }
   * })
   */
  upsert<T extends ManualPaymentUpsertArgs>(args: Prisma.SelectSubset<T, ManualPaymentUpsertArgs<ExtArgs>>): Prisma.Prisma__ManualPaymentClient<runtime.Types.Result.GetResult<Prisma.$ManualPaymentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ManualPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentCountArgs} args - Arguments to filter ManualPayments to count.
   * @example
   * // Count the number of ManualPayments
   * const count = await prisma.manualPayment.count({
   *   where: {
   *     // ... the filter for the ManualPayments we want to count
   *   }
   * })
  **/
  count<T extends ManualPaymentCountArgs>(
    args?: Prisma.Subset<T, ManualPaymentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManualPaymentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ManualPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManualPaymentAggregateArgs>(args: Prisma.Subset<T, ManualPaymentAggregateArgs>): Prisma.PrismaPromise<GetManualPaymentAggregateType<T>>

  /**
   * Group by ManualPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualPaymentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManualPaymentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManualPaymentGroupByArgs['orderBy'] }
      : { orderBy?: ManualPaymentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManualPaymentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManualPaymentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ManualPayment model
 */
readonly fields: ManualPaymentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ManualPayment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManualPaymentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ManualPayment model
 */
export interface ManualPaymentFieldRefs {
  readonly id: Prisma.FieldRef<"ManualPayment", 'Int'>
  readonly userId: Prisma.FieldRef<"ManualPayment", 'Int'>
  readonly status: Prisma.FieldRef<"ManualPayment", 'String'>
  readonly createdAt: Prisma.FieldRef<"ManualPayment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ManualPayment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ManualPayment findUnique
 */
export type ManualPaymentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter, which ManualPayment to fetch.
   */
  where: Prisma.ManualPaymentWhereUniqueInput
}

/**
 * ManualPayment findUniqueOrThrow
 */
export type ManualPaymentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter, which ManualPayment to fetch.
   */
  where: Prisma.ManualPaymentWhereUniqueInput
}

/**
 * ManualPayment findFirst
 */
export type ManualPaymentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter, which ManualPayment to fetch.
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualPayments to fetch.
   */
  orderBy?: Prisma.ManualPaymentOrderByWithRelationInput | Prisma.ManualPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManualPayments.
   */
  cursor?: Prisma.ManualPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManualPayments.
   */
  distinct?: Prisma.ManualPaymentScalarFieldEnum | Prisma.ManualPaymentScalarFieldEnum[]
}

/**
 * ManualPayment findFirstOrThrow
 */
export type ManualPaymentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter, which ManualPayment to fetch.
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualPayments to fetch.
   */
  orderBy?: Prisma.ManualPaymentOrderByWithRelationInput | Prisma.ManualPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManualPayments.
   */
  cursor?: Prisma.ManualPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManualPayments.
   */
  distinct?: Prisma.ManualPaymentScalarFieldEnum | Prisma.ManualPaymentScalarFieldEnum[]
}

/**
 * ManualPayment findMany
 */
export type ManualPaymentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter, which ManualPayments to fetch.
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualPayments to fetch.
   */
  orderBy?: Prisma.ManualPaymentOrderByWithRelationInput | Prisma.ManualPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ManualPayments.
   */
  cursor?: Prisma.ManualPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualPayments.
   */
  skip?: number
  distinct?: Prisma.ManualPaymentScalarFieldEnum | Prisma.ManualPaymentScalarFieldEnum[]
}

/**
 * ManualPayment create
 */
export type ManualPaymentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * The data needed to create a ManualPayment.
   */
  data: Prisma.XOR<Prisma.ManualPaymentCreateInput, Prisma.ManualPaymentUncheckedCreateInput>
}

/**
 * ManualPayment createMany
 */
export type ManualPaymentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ManualPayments.
   */
  data: Prisma.ManualPaymentCreateManyInput | Prisma.ManualPaymentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManualPayment createManyAndReturn
 */
export type ManualPaymentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * The data used to create many ManualPayments.
   */
  data: Prisma.ManualPaymentCreateManyInput | Prisma.ManualPaymentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ManualPayment update
 */
export type ManualPaymentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * The data needed to update a ManualPayment.
   */
  data: Prisma.XOR<Prisma.ManualPaymentUpdateInput, Prisma.ManualPaymentUncheckedUpdateInput>
  /**
   * Choose, which ManualPayment to update.
   */
  where: Prisma.ManualPaymentWhereUniqueInput
}

/**
 * ManualPayment updateMany
 */
export type ManualPaymentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ManualPayments.
   */
  data: Prisma.XOR<Prisma.ManualPaymentUpdateManyMutationInput, Prisma.ManualPaymentUncheckedUpdateManyInput>
  /**
   * Filter which ManualPayments to update
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * Limit how many ManualPayments to update.
   */
  limit?: number
}

/**
 * ManualPayment updateManyAndReturn
 */
export type ManualPaymentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * The data used to update ManualPayments.
   */
  data: Prisma.XOR<Prisma.ManualPaymentUpdateManyMutationInput, Prisma.ManualPaymentUncheckedUpdateManyInput>
  /**
   * Filter which ManualPayments to update
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * Limit how many ManualPayments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ManualPayment upsert
 */
export type ManualPaymentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * The filter to search for the ManualPayment to update in case it exists.
   */
  where: Prisma.ManualPaymentWhereUniqueInput
  /**
   * In case the ManualPayment found by the `where` argument doesn't exist, create a new ManualPayment with this data.
   */
  create: Prisma.XOR<Prisma.ManualPaymentCreateInput, Prisma.ManualPaymentUncheckedCreateInput>
  /**
   * In case the ManualPayment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManualPaymentUpdateInput, Prisma.ManualPaymentUncheckedUpdateInput>
}

/**
 * ManualPayment delete
 */
export type ManualPaymentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
  /**
   * Filter which ManualPayment to delete.
   */
  where: Prisma.ManualPaymentWhereUniqueInput
}

/**
 * ManualPayment deleteMany
 */
export type ManualPaymentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManualPayments to delete
   */
  where?: Prisma.ManualPaymentWhereInput
  /**
   * Limit how many ManualPayments to delete.
   */
  limit?: number
}

/**
 * ManualPayment without action
 */
export type ManualPaymentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualPayment
   */
  select?: Prisma.ManualPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualPayment
   */
  omit?: Prisma.ManualPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualPaymentInclude<ExtArgs> | null
}
