
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReminderJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReminderJob
 * 
 */
export type ReminderJobModel = runtime.Types.Result.DefaultSelection<Prisma.$ReminderJobPayload>

export type AggregateReminderJob = {
  _count: ReminderJobCountAggregateOutputType | null
  _avg: ReminderJobAvgAggregateOutputType | null
  _sum: ReminderJobSumAggregateOutputType | null
  _min: ReminderJobMinAggregateOutputType | null
  _max: ReminderJobMaxAggregateOutputType | null
}

export type ReminderJobAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  telegramId: number | null
  snoozeCount: number | null
  autoNudgeCount: number | null
}

export type ReminderJobSumAggregateOutputType = {
  id: number | null
  userId: number | null
  telegramId: bigint | null
  snoozeCount: number | null
  autoNudgeCount: number | null
}

export type ReminderJobMinAggregateOutputType = {
  id: number | null
  userId: number | null
  telegramId: bigint | null
  scheduledFor: Date | null
  status: string | null
  snoozeCount: number | null
  autoNudgeCount: number | null
  logDate: string | null
  bucketSent: string | null
  convertedAt: Date | null
  createdAt: Date | null
}

export type ReminderJobMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  telegramId: bigint | null
  scheduledFor: Date | null
  status: string | null
  snoozeCount: number | null
  autoNudgeCount: number | null
  logDate: string | null
  bucketSent: string | null
  convertedAt: Date | null
  createdAt: Date | null
}

export type ReminderJobCountAggregateOutputType = {
  id: number
  userId: number
  telegramId: number
  scheduledFor: number
  status: number
  snoozeCount: number
  autoNudgeCount: number
  logDate: number
  bucketSent: number
  convertedAt: number
  createdAt: number
  _all: number
}


export type ReminderJobAvgAggregateInputType = {
  id?: true
  userId?: true
  telegramId?: true
  snoozeCount?: true
  autoNudgeCount?: true
}

export type ReminderJobSumAggregateInputType = {
  id?: true
  userId?: true
  telegramId?: true
  snoozeCount?: true
  autoNudgeCount?: true
}

export type ReminderJobMinAggregateInputType = {
  id?: true
  userId?: true
  telegramId?: true
  scheduledFor?: true
  status?: true
  snoozeCount?: true
  autoNudgeCount?: true
  logDate?: true
  bucketSent?: true
  convertedAt?: true
  createdAt?: true
}

export type ReminderJobMaxAggregateInputType = {
  id?: true
  userId?: true
  telegramId?: true
  scheduledFor?: true
  status?: true
  snoozeCount?: true
  autoNudgeCount?: true
  logDate?: true
  bucketSent?: true
  convertedAt?: true
  createdAt?: true
}

export type ReminderJobCountAggregateInputType = {
  id?: true
  userId?: true
  telegramId?: true
  scheduledFor?: true
  status?: true
  snoozeCount?: true
  autoNudgeCount?: true
  logDate?: true
  bucketSent?: true
  convertedAt?: true
  createdAt?: true
  _all?: true
}

export type ReminderJobAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReminderJob to aggregate.
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderJobs to fetch.
   */
  orderBy?: Prisma.ReminderJobOrderByWithRelationInput | Prisma.ReminderJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReminderJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReminderJobs
  **/
  _count?: true | ReminderJobCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReminderJobAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReminderJobSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReminderJobMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReminderJobMaxAggregateInputType
}

export type GetReminderJobAggregateType<T extends ReminderJobAggregateArgs> = {
      [P in keyof T & keyof AggregateReminderJob]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReminderJob[P]>
    : Prisma.GetScalarType<T[P], AggregateReminderJob[P]>
}




export type ReminderJobGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReminderJobWhereInput
  orderBy?: Prisma.ReminderJobOrderByWithAggregationInput | Prisma.ReminderJobOrderByWithAggregationInput[]
  by: Prisma.ReminderJobScalarFieldEnum[] | Prisma.ReminderJobScalarFieldEnum
  having?: Prisma.ReminderJobScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReminderJobCountAggregateInputType | true
  _avg?: ReminderJobAvgAggregateInputType
  _sum?: ReminderJobSumAggregateInputType
  _min?: ReminderJobMinAggregateInputType
  _max?: ReminderJobMaxAggregateInputType
}

export type ReminderJobGroupByOutputType = {
  id: number
  userId: number
  telegramId: bigint
  scheduledFor: Date
  status: string
  snoozeCount: number
  autoNudgeCount: number
  logDate: string | null
  bucketSent: string | null
  convertedAt: Date | null
  createdAt: Date
  _count: ReminderJobCountAggregateOutputType | null
  _avg: ReminderJobAvgAggregateOutputType | null
  _sum: ReminderJobSumAggregateOutputType | null
  _min: ReminderJobMinAggregateOutputType | null
  _max: ReminderJobMaxAggregateOutputType | null
}

type GetReminderJobGroupByPayload<T extends ReminderJobGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReminderJobGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReminderJobGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReminderJobGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReminderJobGroupByOutputType[P]>
      }
    >
  >



export type ReminderJobWhereInput = {
  AND?: Prisma.ReminderJobWhereInput | Prisma.ReminderJobWhereInput[]
  OR?: Prisma.ReminderJobWhereInput[]
  NOT?: Prisma.ReminderJobWhereInput | Prisma.ReminderJobWhereInput[]
  id?: Prisma.IntFilter<"ReminderJob"> | number
  userId?: Prisma.IntFilter<"ReminderJob"> | number
  telegramId?: Prisma.BigIntFilter<"ReminderJob"> | bigint | number
  scheduledFor?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
  status?: Prisma.StringFilter<"ReminderJob"> | string
  snoozeCount?: Prisma.IntFilter<"ReminderJob"> | number
  autoNudgeCount?: Prisma.IntFilter<"ReminderJob"> | number
  logDate?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  bucketSent?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"ReminderJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ReminderJobOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  scheduledFor?: Prisma.SortOrder
  status?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
  logDate?: Prisma.SortOrderInput | Prisma.SortOrder
  bucketSent?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type ReminderJobWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ReminderJobWhereInput | Prisma.ReminderJobWhereInput[]
  OR?: Prisma.ReminderJobWhereInput[]
  NOT?: Prisma.ReminderJobWhereInput | Prisma.ReminderJobWhereInput[]
  userId?: Prisma.IntFilter<"ReminderJob"> | number
  telegramId?: Prisma.BigIntFilter<"ReminderJob"> | bigint | number
  scheduledFor?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
  status?: Prisma.StringFilter<"ReminderJob"> | string
  snoozeCount?: Prisma.IntFilter<"ReminderJob"> | number
  autoNudgeCount?: Prisma.IntFilter<"ReminderJob"> | number
  logDate?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  bucketSent?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"ReminderJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ReminderJobOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  scheduledFor?: Prisma.SortOrder
  status?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
  logDate?: Prisma.SortOrderInput | Prisma.SortOrder
  bucketSent?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ReminderJobCountOrderByAggregateInput
  _avg?: Prisma.ReminderJobAvgOrderByAggregateInput
  _max?: Prisma.ReminderJobMaxOrderByAggregateInput
  _min?: Prisma.ReminderJobMinOrderByAggregateInput
  _sum?: Prisma.ReminderJobSumOrderByAggregateInput
}

export type ReminderJobScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReminderJobScalarWhereWithAggregatesInput | Prisma.ReminderJobScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReminderJobScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReminderJobScalarWhereWithAggregatesInput | Prisma.ReminderJobScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReminderJob"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ReminderJob"> | number
  telegramId?: Prisma.BigIntWithAggregatesFilter<"ReminderJob"> | bigint | number
  scheduledFor?: Prisma.DateTimeWithAggregatesFilter<"ReminderJob"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"ReminderJob"> | string
  snoozeCount?: Prisma.IntWithAggregatesFilter<"ReminderJob"> | number
  autoNudgeCount?: Prisma.IntWithAggregatesFilter<"ReminderJob"> | number
  logDate?: Prisma.StringNullableWithAggregatesFilter<"ReminderJob"> | string | null
  bucketSent?: Prisma.StringNullableWithAggregatesFilter<"ReminderJob"> | string | null
  convertedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReminderJob"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReminderJob"> | Date | string
}

export type ReminderJobCreateInput = {
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutReminderJobsInput
}

export type ReminderJobUncheckedCreateInput = {
  id?: number
  userId: number
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
}

export type ReminderJobUpdateInput = {
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutReminderJobsNestedInput
}

export type ReminderJobUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderJobCreateManyInput = {
  id?: number
  userId: number
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
}

export type ReminderJobUpdateManyMutationInput = {
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderJobUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderJobListRelationFilter = {
  every?: Prisma.ReminderJobWhereInput
  some?: Prisma.ReminderJobWhereInput
  none?: Prisma.ReminderJobWhereInput
}

export type ReminderJobOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReminderJobCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  scheduledFor?: Prisma.SortOrder
  status?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
  logDate?: Prisma.SortOrder
  bucketSent?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ReminderJobAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
}

export type ReminderJobMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  scheduledFor?: Prisma.SortOrder
  status?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
  logDate?: Prisma.SortOrder
  bucketSent?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ReminderJobMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  scheduledFor?: Prisma.SortOrder
  status?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
  logDate?: Prisma.SortOrder
  bucketSent?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ReminderJobSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  snoozeCount?: Prisma.SortOrder
  autoNudgeCount?: Prisma.SortOrder
}

export type ReminderJobCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput> | Prisma.ReminderJobCreateWithoutUserInput[] | Prisma.ReminderJobUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReminderJobCreateOrConnectWithoutUserInput | Prisma.ReminderJobCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReminderJobCreateManyUserInputEnvelope
  connect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
}

export type ReminderJobUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput> | Prisma.ReminderJobCreateWithoutUserInput[] | Prisma.ReminderJobUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReminderJobCreateOrConnectWithoutUserInput | Prisma.ReminderJobCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReminderJobCreateManyUserInputEnvelope
  connect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
}

export type ReminderJobUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput> | Prisma.ReminderJobCreateWithoutUserInput[] | Prisma.ReminderJobUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReminderJobCreateOrConnectWithoutUserInput | Prisma.ReminderJobCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReminderJobUpsertWithWhereUniqueWithoutUserInput | Prisma.ReminderJobUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReminderJobCreateManyUserInputEnvelope
  set?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  disconnect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  delete?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  connect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  update?: Prisma.ReminderJobUpdateWithWhereUniqueWithoutUserInput | Prisma.ReminderJobUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReminderJobUpdateManyWithWhereWithoutUserInput | Prisma.ReminderJobUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReminderJobScalarWhereInput | Prisma.ReminderJobScalarWhereInput[]
}

export type ReminderJobUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput> | Prisma.ReminderJobCreateWithoutUserInput[] | Prisma.ReminderJobUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReminderJobCreateOrConnectWithoutUserInput | Prisma.ReminderJobCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReminderJobUpsertWithWhereUniqueWithoutUserInput | Prisma.ReminderJobUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReminderJobCreateManyUserInputEnvelope
  set?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  disconnect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  delete?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  connect?: Prisma.ReminderJobWhereUniqueInput | Prisma.ReminderJobWhereUniqueInput[]
  update?: Prisma.ReminderJobUpdateWithWhereUniqueWithoutUserInput | Prisma.ReminderJobUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReminderJobUpdateManyWithWhereWithoutUserInput | Prisma.ReminderJobUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReminderJobScalarWhereInput | Prisma.ReminderJobScalarWhereInput[]
}

export type ReminderJobCreateWithoutUserInput = {
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
}

export type ReminderJobUncheckedCreateWithoutUserInput = {
  id?: number
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
}

export type ReminderJobCreateOrConnectWithoutUserInput = {
  where: Prisma.ReminderJobWhereUniqueInput
  create: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput>
}

export type ReminderJobCreateManyUserInputEnvelope = {
  data: Prisma.ReminderJobCreateManyUserInput | Prisma.ReminderJobCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ReminderJobUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReminderJobWhereUniqueInput
  update: Prisma.XOR<Prisma.ReminderJobUpdateWithoutUserInput, Prisma.ReminderJobUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ReminderJobCreateWithoutUserInput, Prisma.ReminderJobUncheckedCreateWithoutUserInput>
}

export type ReminderJobUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReminderJobWhereUniqueInput
  data: Prisma.XOR<Prisma.ReminderJobUpdateWithoutUserInput, Prisma.ReminderJobUncheckedUpdateWithoutUserInput>
}

export type ReminderJobUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ReminderJobScalarWhereInput
  data: Prisma.XOR<Prisma.ReminderJobUpdateManyMutationInput, Prisma.ReminderJobUncheckedUpdateManyWithoutUserInput>
}

export type ReminderJobScalarWhereInput = {
  AND?: Prisma.ReminderJobScalarWhereInput | Prisma.ReminderJobScalarWhereInput[]
  OR?: Prisma.ReminderJobScalarWhereInput[]
  NOT?: Prisma.ReminderJobScalarWhereInput | Prisma.ReminderJobScalarWhereInput[]
  id?: Prisma.IntFilter<"ReminderJob"> | number
  userId?: Prisma.IntFilter<"ReminderJob"> | number
  telegramId?: Prisma.BigIntFilter<"ReminderJob"> | bigint | number
  scheduledFor?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
  status?: Prisma.StringFilter<"ReminderJob"> | string
  snoozeCount?: Prisma.IntFilter<"ReminderJob"> | number
  autoNudgeCount?: Prisma.IntFilter<"ReminderJob"> | number
  logDate?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  bucketSent?: Prisma.StringNullableFilter<"ReminderJob"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"ReminderJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ReminderJob"> | Date | string
}

export type ReminderJobCreateManyUserInput = {
  id?: number
  telegramId: bigint | number
  scheduledFor: Date | string
  status: string
  snoozeCount?: number
  autoNudgeCount?: number
  logDate?: string | null
  bucketSent?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
}

export type ReminderJobUpdateWithoutUserInput = {
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderJobUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReminderJobUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scheduledFor?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  snoozeCount?: Prisma.IntFieldUpdateOperationsInput | number
  autoNudgeCount?: Prisma.IntFieldUpdateOperationsInput | number
  logDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bucketSent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ReminderJobSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  telegramId?: boolean
  scheduledFor?: boolean
  status?: boolean
  snoozeCount?: boolean
  autoNudgeCount?: boolean
  logDate?: boolean
  bucketSent?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminderJob"]>

export type ReminderJobSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  telegramId?: boolean
  scheduledFor?: boolean
  status?: boolean
  snoozeCount?: boolean
  autoNudgeCount?: boolean
  logDate?: boolean
  bucketSent?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminderJob"]>

export type ReminderJobSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  telegramId?: boolean
  scheduledFor?: boolean
  status?: boolean
  snoozeCount?: boolean
  autoNudgeCount?: boolean
  logDate?: boolean
  bucketSent?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reminderJob"]>

export type ReminderJobSelectScalar = {
  id?: boolean
  userId?: boolean
  telegramId?: boolean
  scheduledFor?: boolean
  status?: boolean
  snoozeCount?: boolean
  autoNudgeCount?: boolean
  logDate?: boolean
  bucketSent?: boolean
  convertedAt?: boolean
  createdAt?: boolean
}

export type ReminderJobOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "telegramId" | "scheduledFor" | "status" | "snoozeCount" | "autoNudgeCount" | "logDate" | "bucketSent" | "convertedAt" | "createdAt", ExtArgs["result"]["reminderJob"]>
export type ReminderJobInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReminderJobIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ReminderJobIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ReminderJobPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReminderJob"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    telegramId: bigint
    scheduledFor: Date
    status: string
    snoozeCount: number
    autoNudgeCount: number
    logDate: string | null
    bucketSent: string | null
    convertedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["reminderJob"]>
  composites: {}
}

export type ReminderJobGetPayload<S extends boolean | null | undefined | ReminderJobDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload, S>

export type ReminderJobCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReminderJobFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReminderJobCountAggregateInputType | true
  }

export interface ReminderJobDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReminderJob'], meta: { name: 'ReminderJob' } }
  /**
   * Find zero or one ReminderJob that matches the filter.
   * @param {ReminderJobFindUniqueArgs} args - Arguments to find a ReminderJob
   * @example
   * // Get one ReminderJob
   * const reminderJob = await prisma.reminderJob.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReminderJobFindUniqueArgs>(args: Prisma.SelectSubset<T, ReminderJobFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReminderJob that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReminderJobFindUniqueOrThrowArgs} args - Arguments to find a ReminderJob
   * @example
   * // Get one ReminderJob
   * const reminderJob = await prisma.reminderJob.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReminderJobFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReminderJobFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReminderJob that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobFindFirstArgs} args - Arguments to find a ReminderJob
   * @example
   * // Get one ReminderJob
   * const reminderJob = await prisma.reminderJob.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReminderJobFindFirstArgs>(args?: Prisma.SelectSubset<T, ReminderJobFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReminderJob that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobFindFirstOrThrowArgs} args - Arguments to find a ReminderJob
   * @example
   * // Get one ReminderJob
   * const reminderJob = await prisma.reminderJob.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReminderJobFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReminderJobFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReminderJobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReminderJobs
   * const reminderJobs = await prisma.reminderJob.findMany()
   * 
   * // Get first 10 ReminderJobs
   * const reminderJobs = await prisma.reminderJob.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reminderJobWithIdOnly = await prisma.reminderJob.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReminderJobFindManyArgs>(args?: Prisma.SelectSubset<T, ReminderJobFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReminderJob.
   * @param {ReminderJobCreateArgs} args - Arguments to create a ReminderJob.
   * @example
   * // Create one ReminderJob
   * const ReminderJob = await prisma.reminderJob.create({
   *   data: {
   *     // ... data to create a ReminderJob
   *   }
   * })
   * 
   */
  create<T extends ReminderJobCreateArgs>(args: Prisma.SelectSubset<T, ReminderJobCreateArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReminderJobs.
   * @param {ReminderJobCreateManyArgs} args - Arguments to create many ReminderJobs.
   * @example
   * // Create many ReminderJobs
   * const reminderJob = await prisma.reminderJob.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReminderJobCreateManyArgs>(args?: Prisma.SelectSubset<T, ReminderJobCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReminderJobs and returns the data saved in the database.
   * @param {ReminderJobCreateManyAndReturnArgs} args - Arguments to create many ReminderJobs.
   * @example
   * // Create many ReminderJobs
   * const reminderJob = await prisma.reminderJob.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReminderJobs and only return the `id`
   * const reminderJobWithIdOnly = await prisma.reminderJob.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReminderJobCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReminderJobCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReminderJob.
   * @param {ReminderJobDeleteArgs} args - Arguments to delete one ReminderJob.
   * @example
   * // Delete one ReminderJob
   * const ReminderJob = await prisma.reminderJob.delete({
   *   where: {
   *     // ... filter to delete one ReminderJob
   *   }
   * })
   * 
   */
  delete<T extends ReminderJobDeleteArgs>(args: Prisma.SelectSubset<T, ReminderJobDeleteArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReminderJob.
   * @param {ReminderJobUpdateArgs} args - Arguments to update one ReminderJob.
   * @example
   * // Update one ReminderJob
   * const reminderJob = await prisma.reminderJob.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReminderJobUpdateArgs>(args: Prisma.SelectSubset<T, ReminderJobUpdateArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReminderJobs.
   * @param {ReminderJobDeleteManyArgs} args - Arguments to filter ReminderJobs to delete.
   * @example
   * // Delete a few ReminderJobs
   * const { count } = await prisma.reminderJob.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReminderJobDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReminderJobDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReminderJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReminderJobs
   * const reminderJob = await prisma.reminderJob.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReminderJobUpdateManyArgs>(args: Prisma.SelectSubset<T, ReminderJobUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReminderJobs and returns the data updated in the database.
   * @param {ReminderJobUpdateManyAndReturnArgs} args - Arguments to update many ReminderJobs.
   * @example
   * // Update many ReminderJobs
   * const reminderJob = await prisma.reminderJob.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReminderJobs and only return the `id`
   * const reminderJobWithIdOnly = await prisma.reminderJob.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReminderJobUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReminderJobUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReminderJob.
   * @param {ReminderJobUpsertArgs} args - Arguments to update or create a ReminderJob.
   * @example
   * // Update or create a ReminderJob
   * const reminderJob = await prisma.reminderJob.upsert({
   *   create: {
   *     // ... data to create a ReminderJob
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReminderJob we want to update
   *   }
   * })
   */
  upsert<T extends ReminderJobUpsertArgs>(args: Prisma.SelectSubset<T, ReminderJobUpsertArgs<ExtArgs>>): Prisma.Prisma__ReminderJobClient<runtime.Types.Result.GetResult<Prisma.$ReminderJobPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReminderJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobCountArgs} args - Arguments to filter ReminderJobs to count.
   * @example
   * // Count the number of ReminderJobs
   * const count = await prisma.reminderJob.count({
   *   where: {
   *     // ... the filter for the ReminderJobs we want to count
   *   }
   * })
  **/
  count<T extends ReminderJobCountArgs>(
    args?: Prisma.Subset<T, ReminderJobCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReminderJobCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReminderJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReminderJobAggregateArgs>(args: Prisma.Subset<T, ReminderJobAggregateArgs>): Prisma.PrismaPromise<GetReminderJobAggregateType<T>>

  /**
   * Group by ReminderJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReminderJobGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReminderJobGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReminderJobGroupByArgs['orderBy'] }
      : { orderBy?: ReminderJobGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReminderJobGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReminderJobGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReminderJob model
 */
readonly fields: ReminderJobFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReminderJob.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReminderJobClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReminderJob model
 */
export interface ReminderJobFieldRefs {
  readonly id: Prisma.FieldRef<"ReminderJob", 'Int'>
  readonly userId: Prisma.FieldRef<"ReminderJob", 'Int'>
  readonly telegramId: Prisma.FieldRef<"ReminderJob", 'BigInt'>
  readonly scheduledFor: Prisma.FieldRef<"ReminderJob", 'DateTime'>
  readonly status: Prisma.FieldRef<"ReminderJob", 'String'>
  readonly snoozeCount: Prisma.FieldRef<"ReminderJob", 'Int'>
  readonly autoNudgeCount: Prisma.FieldRef<"ReminderJob", 'Int'>
  readonly logDate: Prisma.FieldRef<"ReminderJob", 'String'>
  readonly bucketSent: Prisma.FieldRef<"ReminderJob", 'String'>
  readonly convertedAt: Prisma.FieldRef<"ReminderJob", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ReminderJob", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReminderJob findUnique
 */
export type ReminderJobFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter, which ReminderJob to fetch.
   */
  where: Prisma.ReminderJobWhereUniqueInput
}

/**
 * ReminderJob findUniqueOrThrow
 */
export type ReminderJobFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter, which ReminderJob to fetch.
   */
  where: Prisma.ReminderJobWhereUniqueInput
}

/**
 * ReminderJob findFirst
 */
export type ReminderJobFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter, which ReminderJob to fetch.
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderJobs to fetch.
   */
  orderBy?: Prisma.ReminderJobOrderByWithRelationInput | Prisma.ReminderJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReminderJobs.
   */
  cursor?: Prisma.ReminderJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReminderJobs.
   */
  distinct?: Prisma.ReminderJobScalarFieldEnum | Prisma.ReminderJobScalarFieldEnum[]
}

/**
 * ReminderJob findFirstOrThrow
 */
export type ReminderJobFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter, which ReminderJob to fetch.
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderJobs to fetch.
   */
  orderBy?: Prisma.ReminderJobOrderByWithRelationInput | Prisma.ReminderJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReminderJobs.
   */
  cursor?: Prisma.ReminderJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReminderJobs.
   */
  distinct?: Prisma.ReminderJobScalarFieldEnum | Prisma.ReminderJobScalarFieldEnum[]
}

/**
 * ReminderJob findMany
 */
export type ReminderJobFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter, which ReminderJobs to fetch.
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReminderJobs to fetch.
   */
  orderBy?: Prisma.ReminderJobOrderByWithRelationInput | Prisma.ReminderJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReminderJobs.
   */
  cursor?: Prisma.ReminderJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReminderJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReminderJobs.
   */
  skip?: number
  distinct?: Prisma.ReminderJobScalarFieldEnum | Prisma.ReminderJobScalarFieldEnum[]
}

/**
 * ReminderJob create
 */
export type ReminderJobCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * The data needed to create a ReminderJob.
   */
  data: Prisma.XOR<Prisma.ReminderJobCreateInput, Prisma.ReminderJobUncheckedCreateInput>
}

/**
 * ReminderJob createMany
 */
export type ReminderJobCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReminderJobs.
   */
  data: Prisma.ReminderJobCreateManyInput | Prisma.ReminderJobCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReminderJob createManyAndReturn
 */
export type ReminderJobCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * The data used to create many ReminderJobs.
   */
  data: Prisma.ReminderJobCreateManyInput | Prisma.ReminderJobCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReminderJob update
 */
export type ReminderJobUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * The data needed to update a ReminderJob.
   */
  data: Prisma.XOR<Prisma.ReminderJobUpdateInput, Prisma.ReminderJobUncheckedUpdateInput>
  /**
   * Choose, which ReminderJob to update.
   */
  where: Prisma.ReminderJobWhereUniqueInput
}

/**
 * ReminderJob updateMany
 */
export type ReminderJobUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReminderJobs.
   */
  data: Prisma.XOR<Prisma.ReminderJobUpdateManyMutationInput, Prisma.ReminderJobUncheckedUpdateManyInput>
  /**
   * Filter which ReminderJobs to update
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * Limit how many ReminderJobs to update.
   */
  limit?: number
}

/**
 * ReminderJob updateManyAndReturn
 */
export type ReminderJobUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * The data used to update ReminderJobs.
   */
  data: Prisma.XOR<Prisma.ReminderJobUpdateManyMutationInput, Prisma.ReminderJobUncheckedUpdateManyInput>
  /**
   * Filter which ReminderJobs to update
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * Limit how many ReminderJobs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReminderJob upsert
 */
export type ReminderJobUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * The filter to search for the ReminderJob to update in case it exists.
   */
  where: Prisma.ReminderJobWhereUniqueInput
  /**
   * In case the ReminderJob found by the `where` argument doesn't exist, create a new ReminderJob with this data.
   */
  create: Prisma.XOR<Prisma.ReminderJobCreateInput, Prisma.ReminderJobUncheckedCreateInput>
  /**
   * In case the ReminderJob was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReminderJobUpdateInput, Prisma.ReminderJobUncheckedUpdateInput>
}

/**
 * ReminderJob delete
 */
export type ReminderJobDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
  /**
   * Filter which ReminderJob to delete.
   */
  where: Prisma.ReminderJobWhereUniqueInput
}

/**
 * ReminderJob deleteMany
 */
export type ReminderJobDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReminderJobs to delete
   */
  where?: Prisma.ReminderJobWhereInput
  /**
   * Limit how many ReminderJobs to delete.
   */
  limit?: number
}

/**
 * ReminderJob without action
 */
export type ReminderJobDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReminderJob
   */
  select?: Prisma.ReminderJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReminderJob
   */
  omit?: Prisma.ReminderJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderJobInclude<ExtArgs> | null
}
