
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReplayEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReplayEvent
 * 
 */
export type ReplayEventModel = runtime.Types.Result.DefaultSelection<Prisma.$ReplayEventPayload>

export type AggregateReplayEvent = {
  _count: ReplayEventCountAggregateOutputType | null
  _avg: ReplayEventAvgAggregateOutputType | null
  _sum: ReplayEventSumAggregateOutputType | null
  _min: ReplayEventMinAggregateOutputType | null
  _max: ReplayEventMaxAggregateOutputType | null
}

export type ReplayEventAvgAggregateOutputType = {
  id: number | null
  telegramId: number | null
}

export type ReplayEventSumAggregateOutputType = {
  id: number | null
  telegramId: bigint | null
}

export type ReplayEventMinAggregateOutputType = {
  id: number | null
  telegramId: bigint | null
  eventType: string | null
  direction: string | null
  payload: string | null
  timestamp: Date | null
}

export type ReplayEventMaxAggregateOutputType = {
  id: number | null
  telegramId: bigint | null
  eventType: string | null
  direction: string | null
  payload: string | null
  timestamp: Date | null
}

export type ReplayEventCountAggregateOutputType = {
  id: number
  telegramId: number
  eventType: number
  direction: number
  payload: number
  timestamp: number
  _all: number
}


export type ReplayEventAvgAggregateInputType = {
  id?: true
  telegramId?: true
}

export type ReplayEventSumAggregateInputType = {
  id?: true
  telegramId?: true
}

export type ReplayEventMinAggregateInputType = {
  id?: true
  telegramId?: true
  eventType?: true
  direction?: true
  payload?: true
  timestamp?: true
}

export type ReplayEventMaxAggregateInputType = {
  id?: true
  telegramId?: true
  eventType?: true
  direction?: true
  payload?: true
  timestamp?: true
}

export type ReplayEventCountAggregateInputType = {
  id?: true
  telegramId?: true
  eventType?: true
  direction?: true
  payload?: true
  timestamp?: true
  _all?: true
}

export type ReplayEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReplayEvent to aggregate.
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplayEvents to fetch.
   */
  orderBy?: Prisma.ReplayEventOrderByWithRelationInput | Prisma.ReplayEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReplayEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplayEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplayEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReplayEvents
  **/
  _count?: true | ReplayEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReplayEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReplayEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReplayEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReplayEventMaxAggregateInputType
}

export type GetReplayEventAggregateType<T extends ReplayEventAggregateArgs> = {
      [P in keyof T & keyof AggregateReplayEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReplayEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateReplayEvent[P]>
}




export type ReplayEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReplayEventWhereInput
  orderBy?: Prisma.ReplayEventOrderByWithAggregationInput | Prisma.ReplayEventOrderByWithAggregationInput[]
  by: Prisma.ReplayEventScalarFieldEnum[] | Prisma.ReplayEventScalarFieldEnum
  having?: Prisma.ReplayEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReplayEventCountAggregateInputType | true
  _avg?: ReplayEventAvgAggregateInputType
  _sum?: ReplayEventSumAggregateInputType
  _min?: ReplayEventMinAggregateInputType
  _max?: ReplayEventMaxAggregateInputType
}

export type ReplayEventGroupByOutputType = {
  id: number
  telegramId: bigint
  eventType: string
  direction: string
  payload: string
  timestamp: Date
  _count: ReplayEventCountAggregateOutputType | null
  _avg: ReplayEventAvgAggregateOutputType | null
  _sum: ReplayEventSumAggregateOutputType | null
  _min: ReplayEventMinAggregateOutputType | null
  _max: ReplayEventMaxAggregateOutputType | null
}

export type GetReplayEventGroupByPayload<T extends ReplayEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReplayEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReplayEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReplayEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReplayEventGroupByOutputType[P]>
      }
    >
  >



export type ReplayEventWhereInput = {
  AND?: Prisma.ReplayEventWhereInput | Prisma.ReplayEventWhereInput[]
  OR?: Prisma.ReplayEventWhereInput[]
  NOT?: Prisma.ReplayEventWhereInput | Prisma.ReplayEventWhereInput[]
  id?: Prisma.IntFilter<"ReplayEvent"> | number
  telegramId?: Prisma.BigIntFilter<"ReplayEvent"> | bigint | number
  eventType?: Prisma.StringFilter<"ReplayEvent"> | string
  direction?: Prisma.StringFilter<"ReplayEvent"> | string
  payload?: Prisma.StringFilter<"ReplayEvent"> | string
  timestamp?: Prisma.DateTimeFilter<"ReplayEvent"> | Date | string
}

export type ReplayEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type ReplayEventWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ReplayEventWhereInput | Prisma.ReplayEventWhereInput[]
  OR?: Prisma.ReplayEventWhereInput[]
  NOT?: Prisma.ReplayEventWhereInput | Prisma.ReplayEventWhereInput[]
  telegramId?: Prisma.BigIntFilter<"ReplayEvent"> | bigint | number
  eventType?: Prisma.StringFilter<"ReplayEvent"> | string
  direction?: Prisma.StringFilter<"ReplayEvent"> | string
  payload?: Prisma.StringFilter<"ReplayEvent"> | string
  timestamp?: Prisma.DateTimeFilter<"ReplayEvent"> | Date | string
}, "id">

export type ReplayEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.ReplayEventCountOrderByAggregateInput
  _avg?: Prisma.ReplayEventAvgOrderByAggregateInput
  _max?: Prisma.ReplayEventMaxOrderByAggregateInput
  _min?: Prisma.ReplayEventMinOrderByAggregateInput
  _sum?: Prisma.ReplayEventSumOrderByAggregateInput
}

export type ReplayEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReplayEventScalarWhereWithAggregatesInput | Prisma.ReplayEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReplayEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReplayEventScalarWhereWithAggregatesInput | Prisma.ReplayEventScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReplayEvent"> | number
  telegramId?: Prisma.BigIntWithAggregatesFilter<"ReplayEvent"> | bigint | number
  eventType?: Prisma.StringWithAggregatesFilter<"ReplayEvent"> | string
  direction?: Prisma.StringWithAggregatesFilter<"ReplayEvent"> | string
  payload?: Prisma.StringWithAggregatesFilter<"ReplayEvent"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"ReplayEvent"> | Date | string
}

export type ReplayEventCreateInput = {
  telegramId: bigint | number
  eventType: string
  direction: string
  payload: string
  timestamp?: Date | string
}

export type ReplayEventUncheckedCreateInput = {
  id?: number
  telegramId: bigint | number
  eventType: string
  direction: string
  payload: string
  timestamp?: Date | string
}

export type ReplayEventUpdateInput = {
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplayEventUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplayEventCreateManyInput = {
  id?: number
  telegramId: bigint | number
  eventType: string
  direction: string
  payload: string
  timestamp?: Date | string
}

export type ReplayEventUpdateManyMutationInput = {
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplayEventUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  telegramId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  eventType?: Prisma.StringFieldUpdateOperationsInput | string
  direction?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplayEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type ReplayEventAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
}

export type ReplayEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type ReplayEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
  eventType?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type ReplayEventSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  telegramId?: Prisma.SortOrder
}



export type ReplayEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  telegramId?: boolean
  eventType?: boolean
  direction?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["replayEvent"]>

export type ReplayEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  telegramId?: boolean
  eventType?: boolean
  direction?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["replayEvent"]>

export type ReplayEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  telegramId?: boolean
  eventType?: boolean
  direction?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["replayEvent"]>

export type ReplayEventSelectScalar = {
  id?: boolean
  telegramId?: boolean
  eventType?: boolean
  direction?: boolean
  payload?: boolean
  timestamp?: boolean
}

export type ReplayEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "telegramId" | "eventType" | "direction" | "payload" | "timestamp", ExtArgs["result"]["replayEvent"]>

export type $ReplayEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReplayEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    telegramId: bigint
    eventType: string
    direction: string
    payload: string
    timestamp: Date
  }, ExtArgs["result"]["replayEvent"]>
  composites: {}
}

export type ReplayEventGetPayload<S extends boolean | null | undefined | ReplayEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload, S>

export type ReplayEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReplayEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReplayEventCountAggregateInputType | true
  }

export interface ReplayEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReplayEvent'], meta: { name: 'ReplayEvent' } }
  /**
   * Find zero or one ReplayEvent that matches the filter.
   * @param {ReplayEventFindUniqueArgs} args - Arguments to find a ReplayEvent
   * @example
   * // Get one ReplayEvent
   * const replayEvent = await prisma.replayEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReplayEventFindUniqueArgs>(args: Prisma.SelectSubset<T, ReplayEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReplayEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReplayEventFindUniqueOrThrowArgs} args - Arguments to find a ReplayEvent
   * @example
   * // Get one ReplayEvent
   * const replayEvent = await prisma.replayEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReplayEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReplayEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReplayEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventFindFirstArgs} args - Arguments to find a ReplayEvent
   * @example
   * // Get one ReplayEvent
   * const replayEvent = await prisma.replayEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReplayEventFindFirstArgs>(args?: Prisma.SelectSubset<T, ReplayEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReplayEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventFindFirstOrThrowArgs} args - Arguments to find a ReplayEvent
   * @example
   * // Get one ReplayEvent
   * const replayEvent = await prisma.replayEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReplayEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReplayEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReplayEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReplayEvents
   * const replayEvents = await prisma.replayEvent.findMany()
   * 
   * // Get first 10 ReplayEvents
   * const replayEvents = await prisma.replayEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const replayEventWithIdOnly = await prisma.replayEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReplayEventFindManyArgs>(args?: Prisma.SelectSubset<T, ReplayEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReplayEvent.
   * @param {ReplayEventCreateArgs} args - Arguments to create a ReplayEvent.
   * @example
   * // Create one ReplayEvent
   * const ReplayEvent = await prisma.replayEvent.create({
   *   data: {
   *     // ... data to create a ReplayEvent
   *   }
   * })
   * 
   */
  create<T extends ReplayEventCreateArgs>(args: Prisma.SelectSubset<T, ReplayEventCreateArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReplayEvents.
   * @param {ReplayEventCreateManyArgs} args - Arguments to create many ReplayEvents.
   * @example
   * // Create many ReplayEvents
   * const replayEvent = await prisma.replayEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReplayEventCreateManyArgs>(args?: Prisma.SelectSubset<T, ReplayEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReplayEvents and returns the data saved in the database.
   * @param {ReplayEventCreateManyAndReturnArgs} args - Arguments to create many ReplayEvents.
   * @example
   * // Create many ReplayEvents
   * const replayEvent = await prisma.replayEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReplayEvents and only return the `id`
   * const replayEventWithIdOnly = await prisma.replayEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReplayEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReplayEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReplayEvent.
   * @param {ReplayEventDeleteArgs} args - Arguments to delete one ReplayEvent.
   * @example
   * // Delete one ReplayEvent
   * const ReplayEvent = await prisma.replayEvent.delete({
   *   where: {
   *     // ... filter to delete one ReplayEvent
   *   }
   * })
   * 
   */
  delete<T extends ReplayEventDeleteArgs>(args: Prisma.SelectSubset<T, ReplayEventDeleteArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReplayEvent.
   * @param {ReplayEventUpdateArgs} args - Arguments to update one ReplayEvent.
   * @example
   * // Update one ReplayEvent
   * const replayEvent = await prisma.replayEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReplayEventUpdateArgs>(args: Prisma.SelectSubset<T, ReplayEventUpdateArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReplayEvents.
   * @param {ReplayEventDeleteManyArgs} args - Arguments to filter ReplayEvents to delete.
   * @example
   * // Delete a few ReplayEvents
   * const { count } = await prisma.replayEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReplayEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReplayEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReplayEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReplayEvents
   * const replayEvent = await prisma.replayEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReplayEventUpdateManyArgs>(args: Prisma.SelectSubset<T, ReplayEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReplayEvents and returns the data updated in the database.
   * @param {ReplayEventUpdateManyAndReturnArgs} args - Arguments to update many ReplayEvents.
   * @example
   * // Update many ReplayEvents
   * const replayEvent = await prisma.replayEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReplayEvents and only return the `id`
   * const replayEventWithIdOnly = await prisma.replayEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReplayEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReplayEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReplayEvent.
   * @param {ReplayEventUpsertArgs} args - Arguments to update or create a ReplayEvent.
   * @example
   * // Update or create a ReplayEvent
   * const replayEvent = await prisma.replayEvent.upsert({
   *   create: {
   *     // ... data to create a ReplayEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReplayEvent we want to update
   *   }
   * })
   */
  upsert<T extends ReplayEventUpsertArgs>(args: Prisma.SelectSubset<T, ReplayEventUpsertArgs<ExtArgs>>): Prisma.Prisma__ReplayEventClient<runtime.Types.Result.GetResult<Prisma.$ReplayEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReplayEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventCountArgs} args - Arguments to filter ReplayEvents to count.
   * @example
   * // Count the number of ReplayEvents
   * const count = await prisma.replayEvent.count({
   *   where: {
   *     // ... the filter for the ReplayEvents we want to count
   *   }
   * })
  **/
  count<T extends ReplayEventCountArgs>(
    args?: Prisma.Subset<T, ReplayEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReplayEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReplayEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReplayEventAggregateArgs>(args: Prisma.Subset<T, ReplayEventAggregateArgs>): Prisma.PrismaPromise<GetReplayEventAggregateType<T>>

  /**
   * Group by ReplayEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplayEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReplayEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReplayEventGroupByArgs['orderBy'] }
      : { orderBy?: ReplayEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReplayEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReplayEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReplayEvent model
 */
readonly fields: ReplayEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReplayEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReplayEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReplayEvent model
 */
export interface ReplayEventFieldRefs {
  readonly id: Prisma.FieldRef<"ReplayEvent", 'Int'>
  readonly telegramId: Prisma.FieldRef<"ReplayEvent", 'BigInt'>
  readonly eventType: Prisma.FieldRef<"ReplayEvent", 'String'>
  readonly direction: Prisma.FieldRef<"ReplayEvent", 'String'>
  readonly payload: Prisma.FieldRef<"ReplayEvent", 'String'>
  readonly timestamp: Prisma.FieldRef<"ReplayEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReplayEvent findUnique
 */
export type ReplayEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter, which ReplayEvent to fetch.
   */
  where: Prisma.ReplayEventWhereUniqueInput
}

/**
 * ReplayEvent findUniqueOrThrow
 */
export type ReplayEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter, which ReplayEvent to fetch.
   */
  where: Prisma.ReplayEventWhereUniqueInput
}

/**
 * ReplayEvent findFirst
 */
export type ReplayEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter, which ReplayEvent to fetch.
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplayEvents to fetch.
   */
  orderBy?: Prisma.ReplayEventOrderByWithRelationInput | Prisma.ReplayEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReplayEvents.
   */
  cursor?: Prisma.ReplayEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplayEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplayEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReplayEvents.
   */
  distinct?: Prisma.ReplayEventScalarFieldEnum | Prisma.ReplayEventScalarFieldEnum[]
}

/**
 * ReplayEvent findFirstOrThrow
 */
export type ReplayEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter, which ReplayEvent to fetch.
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplayEvents to fetch.
   */
  orderBy?: Prisma.ReplayEventOrderByWithRelationInput | Prisma.ReplayEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReplayEvents.
   */
  cursor?: Prisma.ReplayEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplayEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplayEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReplayEvents.
   */
  distinct?: Prisma.ReplayEventScalarFieldEnum | Prisma.ReplayEventScalarFieldEnum[]
}

/**
 * ReplayEvent findMany
 */
export type ReplayEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter, which ReplayEvents to fetch.
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplayEvents to fetch.
   */
  orderBy?: Prisma.ReplayEventOrderByWithRelationInput | Prisma.ReplayEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReplayEvents.
   */
  cursor?: Prisma.ReplayEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplayEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplayEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReplayEvents.
   */
  distinct?: Prisma.ReplayEventScalarFieldEnum | Prisma.ReplayEventScalarFieldEnum[]
}

/**
 * ReplayEvent create
 */
export type ReplayEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * The data needed to create a ReplayEvent.
   */
  data: Prisma.XOR<Prisma.ReplayEventCreateInput, Prisma.ReplayEventUncheckedCreateInput>
}

/**
 * ReplayEvent createMany
 */
export type ReplayEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReplayEvents.
   */
  data: Prisma.ReplayEventCreateManyInput | Prisma.ReplayEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReplayEvent createManyAndReturn
 */
export type ReplayEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * The data used to create many ReplayEvents.
   */
  data: Prisma.ReplayEventCreateManyInput | Prisma.ReplayEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReplayEvent update
 */
export type ReplayEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * The data needed to update a ReplayEvent.
   */
  data: Prisma.XOR<Prisma.ReplayEventUpdateInput, Prisma.ReplayEventUncheckedUpdateInput>
  /**
   * Choose, which ReplayEvent to update.
   */
  where: Prisma.ReplayEventWhereUniqueInput
}

/**
 * ReplayEvent updateMany
 */
export type ReplayEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReplayEvents.
   */
  data: Prisma.XOR<Prisma.ReplayEventUpdateManyMutationInput, Prisma.ReplayEventUncheckedUpdateManyInput>
  /**
   * Filter which ReplayEvents to update
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * Limit how many ReplayEvents to update.
   */
  limit?: number
}

/**
 * ReplayEvent updateManyAndReturn
 */
export type ReplayEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * The data used to update ReplayEvents.
   */
  data: Prisma.XOR<Prisma.ReplayEventUpdateManyMutationInput, Prisma.ReplayEventUncheckedUpdateManyInput>
  /**
   * Filter which ReplayEvents to update
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * Limit how many ReplayEvents to update.
   */
  limit?: number
}

/**
 * ReplayEvent upsert
 */
export type ReplayEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * The filter to search for the ReplayEvent to update in case it exists.
   */
  where: Prisma.ReplayEventWhereUniqueInput
  /**
   * In case the ReplayEvent found by the `where` argument doesn't exist, create a new ReplayEvent with this data.
   */
  create: Prisma.XOR<Prisma.ReplayEventCreateInput, Prisma.ReplayEventUncheckedCreateInput>
  /**
   * In case the ReplayEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReplayEventUpdateInput, Prisma.ReplayEventUncheckedUpdateInput>
}

/**
 * ReplayEvent delete
 */
export type ReplayEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
  /**
   * Filter which ReplayEvent to delete.
   */
  where: Prisma.ReplayEventWhereUniqueInput
}

/**
 * ReplayEvent deleteMany
 */
export type ReplayEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReplayEvents to delete
   */
  where?: Prisma.ReplayEventWhereInput
  /**
   * Limit how many ReplayEvents to delete.
   */
  limit?: number
}

/**
 * ReplayEvent without action
 */
export type ReplayEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplayEvent
   */
  select?: Prisma.ReplayEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplayEvent
   */
  omit?: Prisma.ReplayEventOmit<ExtArgs> | null
}
