
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WeeklyQuote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WeeklyQuote
 * 
 */
export type WeeklyQuoteModel = runtime.Types.Result.DefaultSelection<Prisma.$WeeklyQuotePayload>

export type AggregateWeeklyQuote = {
  _count: WeeklyQuoteCountAggregateOutputType | null
  _avg: WeeklyQuoteAvgAggregateOutputType | null
  _sum: WeeklyQuoteSumAggregateOutputType | null
  _min: WeeklyQuoteMinAggregateOutputType | null
  _max: WeeklyQuoteMaxAggregateOutputType | null
}

export type WeeklyQuoteAvgAggregateOutputType = {
  id: number | null
  weekNumber: number | null
}

export type WeeklyQuoteSumAggregateOutputType = {
  id: number | null
  weekNumber: number | null
}

export type WeeklyQuoteMinAggregateOutputType = {
  id: number | null
  weekNumber: number | null
  quote: string | null
  attribution: string | null
}

export type WeeklyQuoteMaxAggregateOutputType = {
  id: number | null
  weekNumber: number | null
  quote: string | null
  attribution: string | null
}

export type WeeklyQuoteCountAggregateOutputType = {
  id: number
  weekNumber: number
  quote: number
  attribution: number
  _all: number
}


export type WeeklyQuoteAvgAggregateInputType = {
  id?: true
  weekNumber?: true
}

export type WeeklyQuoteSumAggregateInputType = {
  id?: true
  weekNumber?: true
}

export type WeeklyQuoteMinAggregateInputType = {
  id?: true
  weekNumber?: true
  quote?: true
  attribution?: true
}

export type WeeklyQuoteMaxAggregateInputType = {
  id?: true
  weekNumber?: true
  quote?: true
  attribution?: true
}

export type WeeklyQuoteCountAggregateInputType = {
  id?: true
  weekNumber?: true
  quote?: true
  attribution?: true
  _all?: true
}

export type WeeklyQuoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WeeklyQuote to aggregate.
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeeklyQuotes to fetch.
   */
  orderBy?: Prisma.WeeklyQuoteOrderByWithRelationInput | Prisma.WeeklyQuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WeeklyQuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeeklyQuotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeeklyQuotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WeeklyQuotes
  **/
  _count?: true | WeeklyQuoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WeeklyQuoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WeeklyQuoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WeeklyQuoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WeeklyQuoteMaxAggregateInputType
}

export type GetWeeklyQuoteAggregateType<T extends WeeklyQuoteAggregateArgs> = {
      [P in keyof T & keyof AggregateWeeklyQuote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWeeklyQuote[P]>
    : Prisma.GetScalarType<T[P], AggregateWeeklyQuote[P]>
}




export type WeeklyQuoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WeeklyQuoteWhereInput
  orderBy?: Prisma.WeeklyQuoteOrderByWithAggregationInput | Prisma.WeeklyQuoteOrderByWithAggregationInput[]
  by: Prisma.WeeklyQuoteScalarFieldEnum[] | Prisma.WeeklyQuoteScalarFieldEnum
  having?: Prisma.WeeklyQuoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WeeklyQuoteCountAggregateInputType | true
  _avg?: WeeklyQuoteAvgAggregateInputType
  _sum?: WeeklyQuoteSumAggregateInputType
  _min?: WeeklyQuoteMinAggregateInputType
  _max?: WeeklyQuoteMaxAggregateInputType
}

export type WeeklyQuoteGroupByOutputType = {
  id: number
  weekNumber: number
  quote: string
  attribution: string | null
  _count: WeeklyQuoteCountAggregateOutputType | null
  _avg: WeeklyQuoteAvgAggregateOutputType | null
  _sum: WeeklyQuoteSumAggregateOutputType | null
  _min: WeeklyQuoteMinAggregateOutputType | null
  _max: WeeklyQuoteMaxAggregateOutputType | null
}

type GetWeeklyQuoteGroupByPayload<T extends WeeklyQuoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WeeklyQuoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WeeklyQuoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WeeklyQuoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WeeklyQuoteGroupByOutputType[P]>
      }
    >
  >



export type WeeklyQuoteWhereInput = {
  AND?: Prisma.WeeklyQuoteWhereInput | Prisma.WeeklyQuoteWhereInput[]
  OR?: Prisma.WeeklyQuoteWhereInput[]
  NOT?: Prisma.WeeklyQuoteWhereInput | Prisma.WeeklyQuoteWhereInput[]
  id?: Prisma.IntFilter<"WeeklyQuote"> | number
  weekNumber?: Prisma.IntFilter<"WeeklyQuote"> | number
  quote?: Prisma.StringFilter<"WeeklyQuote"> | string
  attribution?: Prisma.StringNullableFilter<"WeeklyQuote"> | string | null
}

export type WeeklyQuoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  quote?: Prisma.SortOrder
  attribution?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type WeeklyQuoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  weekNumber?: number
  AND?: Prisma.WeeklyQuoteWhereInput | Prisma.WeeklyQuoteWhereInput[]
  OR?: Prisma.WeeklyQuoteWhereInput[]
  NOT?: Prisma.WeeklyQuoteWhereInput | Prisma.WeeklyQuoteWhereInput[]
  quote?: Prisma.StringFilter<"WeeklyQuote"> | string
  attribution?: Prisma.StringNullableFilter<"WeeklyQuote"> | string | null
}, "id" | "weekNumber">

export type WeeklyQuoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  quote?: Prisma.SortOrder
  attribution?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.WeeklyQuoteCountOrderByAggregateInput
  _avg?: Prisma.WeeklyQuoteAvgOrderByAggregateInput
  _max?: Prisma.WeeklyQuoteMaxOrderByAggregateInput
  _min?: Prisma.WeeklyQuoteMinOrderByAggregateInput
  _sum?: Prisma.WeeklyQuoteSumOrderByAggregateInput
}

export type WeeklyQuoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.WeeklyQuoteScalarWhereWithAggregatesInput | Prisma.WeeklyQuoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.WeeklyQuoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WeeklyQuoteScalarWhereWithAggregatesInput | Prisma.WeeklyQuoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"WeeklyQuote"> | number
  weekNumber?: Prisma.IntWithAggregatesFilter<"WeeklyQuote"> | number
  quote?: Prisma.StringWithAggregatesFilter<"WeeklyQuote"> | string
  attribution?: Prisma.StringNullableWithAggregatesFilter<"WeeklyQuote"> | string | null
}

export type WeeklyQuoteCreateInput = {
  weekNumber: number
  quote: string
  attribution?: string | null
}

export type WeeklyQuoteUncheckedCreateInput = {
  id?: number
  weekNumber: number
  quote: string
  attribution?: string | null
}

export type WeeklyQuoteUpdateInput = {
  weekNumber?: Prisma.IntFieldUpdateOperationsInput | number
  quote?: Prisma.StringFieldUpdateOperationsInput | string
  attribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WeeklyQuoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.IntFieldUpdateOperationsInput | number
  quote?: Prisma.StringFieldUpdateOperationsInput | string
  attribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WeeklyQuoteCreateManyInput = {
  id?: number
  weekNumber: number
  quote: string
  attribution?: string | null
}

export type WeeklyQuoteUpdateManyMutationInput = {
  weekNumber?: Prisma.IntFieldUpdateOperationsInput | number
  quote?: Prisma.StringFieldUpdateOperationsInput | string
  attribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WeeklyQuoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weekNumber?: Prisma.IntFieldUpdateOperationsInput | number
  quote?: Prisma.StringFieldUpdateOperationsInput | string
  attribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WeeklyQuoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  quote?: Prisma.SortOrder
  attribution?: Prisma.SortOrder
}

export type WeeklyQuoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
}

export type WeeklyQuoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  quote?: Prisma.SortOrder
  attribution?: Prisma.SortOrder
}

export type WeeklyQuoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
  quote?: Prisma.SortOrder
  attribution?: Prisma.SortOrder
}

export type WeeklyQuoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weekNumber?: Prisma.SortOrder
}



export type WeeklyQuoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weekNumber?: boolean
  quote?: boolean
  attribution?: boolean
}, ExtArgs["result"]["weeklyQuote"]>

export type WeeklyQuoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weekNumber?: boolean
  quote?: boolean
  attribution?: boolean
}, ExtArgs["result"]["weeklyQuote"]>

export type WeeklyQuoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weekNumber?: boolean
  quote?: boolean
  attribution?: boolean
}, ExtArgs["result"]["weeklyQuote"]>

export type WeeklyQuoteSelectScalar = {
  id?: boolean
  weekNumber?: boolean
  quote?: boolean
  attribution?: boolean
}

export type WeeklyQuoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "weekNumber" | "quote" | "attribution", ExtArgs["result"]["weeklyQuote"]>

export type $WeeklyQuotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WeeklyQuote"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    weekNumber: number
    quote: string
    attribution: string | null
  }, ExtArgs["result"]["weeklyQuote"]>
  composites: {}
}

export type WeeklyQuoteGetPayload<S extends boolean | null | undefined | WeeklyQuoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload, S>

export type WeeklyQuoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WeeklyQuoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WeeklyQuoteCountAggregateInputType | true
  }

export interface WeeklyQuoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WeeklyQuote'], meta: { name: 'WeeklyQuote' } }
  /**
   * Find zero or one WeeklyQuote that matches the filter.
   * @param {WeeklyQuoteFindUniqueArgs} args - Arguments to find a WeeklyQuote
   * @example
   * // Get one WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WeeklyQuoteFindUniqueArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WeeklyQuote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WeeklyQuoteFindUniqueOrThrowArgs} args - Arguments to find a WeeklyQuote
   * @example
   * // Get one WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WeeklyQuoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WeeklyQuote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteFindFirstArgs} args - Arguments to find a WeeklyQuote
   * @example
   * // Get one WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WeeklyQuoteFindFirstArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WeeklyQuote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteFindFirstOrThrowArgs} args - Arguments to find a WeeklyQuote
   * @example
   * // Get one WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WeeklyQuoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WeeklyQuotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WeeklyQuotes
   * const weeklyQuotes = await prisma.weeklyQuote.findMany()
   * 
   * // Get first 10 WeeklyQuotes
   * const weeklyQuotes = await prisma.weeklyQuote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const weeklyQuoteWithIdOnly = await prisma.weeklyQuote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WeeklyQuoteFindManyArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WeeklyQuote.
   * @param {WeeklyQuoteCreateArgs} args - Arguments to create a WeeklyQuote.
   * @example
   * // Create one WeeklyQuote
   * const WeeklyQuote = await prisma.weeklyQuote.create({
   *   data: {
   *     // ... data to create a WeeklyQuote
   *   }
   * })
   * 
   */
  create<T extends WeeklyQuoteCreateArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteCreateArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WeeklyQuotes.
   * @param {WeeklyQuoteCreateManyArgs} args - Arguments to create many WeeklyQuotes.
   * @example
   * // Create many WeeklyQuotes
   * const weeklyQuote = await prisma.weeklyQuote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WeeklyQuoteCreateManyArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WeeklyQuotes and returns the data saved in the database.
   * @param {WeeklyQuoteCreateManyAndReturnArgs} args - Arguments to create many WeeklyQuotes.
   * @example
   * // Create many WeeklyQuotes
   * const weeklyQuote = await prisma.weeklyQuote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WeeklyQuotes and only return the `id`
   * const weeklyQuoteWithIdOnly = await prisma.weeklyQuote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WeeklyQuoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WeeklyQuote.
   * @param {WeeklyQuoteDeleteArgs} args - Arguments to delete one WeeklyQuote.
   * @example
   * // Delete one WeeklyQuote
   * const WeeklyQuote = await prisma.weeklyQuote.delete({
   *   where: {
   *     // ... filter to delete one WeeklyQuote
   *   }
   * })
   * 
   */
  delete<T extends WeeklyQuoteDeleteArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteDeleteArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WeeklyQuote.
   * @param {WeeklyQuoteUpdateArgs} args - Arguments to update one WeeklyQuote.
   * @example
   * // Update one WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WeeklyQuoteUpdateArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteUpdateArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WeeklyQuotes.
   * @param {WeeklyQuoteDeleteManyArgs} args - Arguments to filter WeeklyQuotes to delete.
   * @example
   * // Delete a few WeeklyQuotes
   * const { count } = await prisma.weeklyQuote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WeeklyQuoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, WeeklyQuoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WeeklyQuotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WeeklyQuotes
   * const weeklyQuote = await prisma.weeklyQuote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WeeklyQuoteUpdateManyArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WeeklyQuotes and returns the data updated in the database.
   * @param {WeeklyQuoteUpdateManyAndReturnArgs} args - Arguments to update many WeeklyQuotes.
   * @example
   * // Update many WeeklyQuotes
   * const weeklyQuote = await prisma.weeklyQuote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WeeklyQuotes and only return the `id`
   * const weeklyQuoteWithIdOnly = await prisma.weeklyQuote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WeeklyQuoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WeeklyQuote.
   * @param {WeeklyQuoteUpsertArgs} args - Arguments to update or create a WeeklyQuote.
   * @example
   * // Update or create a WeeklyQuote
   * const weeklyQuote = await prisma.weeklyQuote.upsert({
   *   create: {
   *     // ... data to create a WeeklyQuote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WeeklyQuote we want to update
   *   }
   * })
   */
  upsert<T extends WeeklyQuoteUpsertArgs>(args: Prisma.SelectSubset<T, WeeklyQuoteUpsertArgs<ExtArgs>>): Prisma.Prisma__WeeklyQuoteClient<runtime.Types.Result.GetResult<Prisma.$WeeklyQuotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WeeklyQuotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteCountArgs} args - Arguments to filter WeeklyQuotes to count.
   * @example
   * // Count the number of WeeklyQuotes
   * const count = await prisma.weeklyQuote.count({
   *   where: {
   *     // ... the filter for the WeeklyQuotes we want to count
   *   }
   * })
  **/
  count<T extends WeeklyQuoteCountArgs>(
    args?: Prisma.Subset<T, WeeklyQuoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WeeklyQuoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WeeklyQuote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WeeklyQuoteAggregateArgs>(args: Prisma.Subset<T, WeeklyQuoteAggregateArgs>): Prisma.PrismaPromise<GetWeeklyQuoteAggregateType<T>>

  /**
   * Group by WeeklyQuote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeeklyQuoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WeeklyQuoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WeeklyQuoteGroupByArgs['orderBy'] }
      : { orderBy?: WeeklyQuoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WeeklyQuoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWeeklyQuoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WeeklyQuote model
 */
readonly fields: WeeklyQuoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WeeklyQuote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WeeklyQuoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WeeklyQuote model
 */
export interface WeeklyQuoteFieldRefs {
  readonly id: Prisma.FieldRef<"WeeklyQuote", 'Int'>
  readonly weekNumber: Prisma.FieldRef<"WeeklyQuote", 'Int'>
  readonly quote: Prisma.FieldRef<"WeeklyQuote", 'String'>
  readonly attribution: Prisma.FieldRef<"WeeklyQuote", 'String'>
}
    

// Custom InputTypes
/**
 * WeeklyQuote findUnique
 */
export type WeeklyQuoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter, which WeeklyQuote to fetch.
   */
  where: Prisma.WeeklyQuoteWhereUniqueInput
}

/**
 * WeeklyQuote findUniqueOrThrow
 */
export type WeeklyQuoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter, which WeeklyQuote to fetch.
   */
  where: Prisma.WeeklyQuoteWhereUniqueInput
}

/**
 * WeeklyQuote findFirst
 */
export type WeeklyQuoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter, which WeeklyQuote to fetch.
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeeklyQuotes to fetch.
   */
  orderBy?: Prisma.WeeklyQuoteOrderByWithRelationInput | Prisma.WeeklyQuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WeeklyQuotes.
   */
  cursor?: Prisma.WeeklyQuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeeklyQuotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeeklyQuotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WeeklyQuotes.
   */
  distinct?: Prisma.WeeklyQuoteScalarFieldEnum | Prisma.WeeklyQuoteScalarFieldEnum[]
}

/**
 * WeeklyQuote findFirstOrThrow
 */
export type WeeklyQuoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter, which WeeklyQuote to fetch.
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeeklyQuotes to fetch.
   */
  orderBy?: Prisma.WeeklyQuoteOrderByWithRelationInput | Prisma.WeeklyQuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WeeklyQuotes.
   */
  cursor?: Prisma.WeeklyQuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeeklyQuotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeeklyQuotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WeeklyQuotes.
   */
  distinct?: Prisma.WeeklyQuoteScalarFieldEnum | Prisma.WeeklyQuoteScalarFieldEnum[]
}

/**
 * WeeklyQuote findMany
 */
export type WeeklyQuoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter, which WeeklyQuotes to fetch.
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WeeklyQuotes to fetch.
   */
  orderBy?: Prisma.WeeklyQuoteOrderByWithRelationInput | Prisma.WeeklyQuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WeeklyQuotes.
   */
  cursor?: Prisma.WeeklyQuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WeeklyQuotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WeeklyQuotes.
   */
  skip?: number
  distinct?: Prisma.WeeklyQuoteScalarFieldEnum | Prisma.WeeklyQuoteScalarFieldEnum[]
}

/**
 * WeeklyQuote create
 */
export type WeeklyQuoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * The data needed to create a WeeklyQuote.
   */
  data: Prisma.XOR<Prisma.WeeklyQuoteCreateInput, Prisma.WeeklyQuoteUncheckedCreateInput>
}

/**
 * WeeklyQuote createMany
 */
export type WeeklyQuoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WeeklyQuotes.
   */
  data: Prisma.WeeklyQuoteCreateManyInput | Prisma.WeeklyQuoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WeeklyQuote createManyAndReturn
 */
export type WeeklyQuoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * The data used to create many WeeklyQuotes.
   */
  data: Prisma.WeeklyQuoteCreateManyInput | Prisma.WeeklyQuoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WeeklyQuote update
 */
export type WeeklyQuoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * The data needed to update a WeeklyQuote.
   */
  data: Prisma.XOR<Prisma.WeeklyQuoteUpdateInput, Prisma.WeeklyQuoteUncheckedUpdateInput>
  /**
   * Choose, which WeeklyQuote to update.
   */
  where: Prisma.WeeklyQuoteWhereUniqueInput
}

/**
 * WeeklyQuote updateMany
 */
export type WeeklyQuoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WeeklyQuotes.
   */
  data: Prisma.XOR<Prisma.WeeklyQuoteUpdateManyMutationInput, Prisma.WeeklyQuoteUncheckedUpdateManyInput>
  /**
   * Filter which WeeklyQuotes to update
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * Limit how many WeeklyQuotes to update.
   */
  limit?: number
}

/**
 * WeeklyQuote updateManyAndReturn
 */
export type WeeklyQuoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * The data used to update WeeklyQuotes.
   */
  data: Prisma.XOR<Prisma.WeeklyQuoteUpdateManyMutationInput, Prisma.WeeklyQuoteUncheckedUpdateManyInput>
  /**
   * Filter which WeeklyQuotes to update
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * Limit how many WeeklyQuotes to update.
   */
  limit?: number
}

/**
 * WeeklyQuote upsert
 */
export type WeeklyQuoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * The filter to search for the WeeklyQuote to update in case it exists.
   */
  where: Prisma.WeeklyQuoteWhereUniqueInput
  /**
   * In case the WeeklyQuote found by the `where` argument doesn't exist, create a new WeeklyQuote with this data.
   */
  create: Prisma.XOR<Prisma.WeeklyQuoteCreateInput, Prisma.WeeklyQuoteUncheckedCreateInput>
  /**
   * In case the WeeklyQuote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WeeklyQuoteUpdateInput, Prisma.WeeklyQuoteUncheckedUpdateInput>
}

/**
 * WeeklyQuote delete
 */
export type WeeklyQuoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
  /**
   * Filter which WeeklyQuote to delete.
   */
  where: Prisma.WeeklyQuoteWhereUniqueInput
}

/**
 * WeeklyQuote deleteMany
 */
export type WeeklyQuoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WeeklyQuotes to delete
   */
  where?: Prisma.WeeklyQuoteWhereInput
  /**
   * Limit how many WeeklyQuotes to delete.
   */
  limit?: number
}

/**
 * WeeklyQuote without action
 */
export type WeeklyQuoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklyQuote
   */
  select?: Prisma.WeeklyQuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklyQuote
   */
  omit?: Prisma.WeeklyQuoteOmit<ExtArgs> | null
}
